# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wallaby', [dirname(__file__)])
        except ImportError:
            import _wallaby
            return _wallaby
        if fp is not None:
            try:
                _mod = imp.load_module('_wallaby', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wallaby = swig_import_helper()
    del swig_import_helper
else:
    import _wallaby
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class IntSensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntSensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntSensor, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_IntSensor
    __del__ = lambda self : None;
    def value(self): return _wallaby.IntSensor_value(self)
IntSensor_swigregister = _wallaby.IntSensor_swigregister
IntSensor_swigregister(IntSensor)

class ShortSensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ShortSensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ShortSensor, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_ShortSensor
    __del__ = lambda self : None;
    def value(self): return _wallaby.ShortSensor_value(self)
ShortSensor_swigregister = _wallaby.ShortSensor_swigregister
ShortSensor_swigregister(ShortSensor)

class UnsignedShortSensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedShortSensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedShortSensor, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_UnsignedShortSensor
    __del__ = lambda self : None;
    def value(self): return _wallaby.UnsignedShortSensor_value(self)
UnsignedShortSensor_swigregister = _wallaby.UnsignedShortSensor_swigregister
UnsignedShortSensor_swigregister(UnsignedShortSensor)

class BoolSensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoolSensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoolSensor, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_BoolSensor
    __del__ = lambda self : None;
    def value(self): return _wallaby.BoolSensor_value(self)
BoolSensor_swigregister = _wallaby.BoolSensor_swigregister
BoolSensor_swigregister(BoolSensor)

class Motor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Motor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Motor, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Motor(*args)
        try: self.this.append(this)
        except: self.this = this
    def clearPositionCounter(self): return _wallaby.Motor_clearPositionCounter(self)
    def moveAtVelocity(self, *args): return _wallaby.Motor_moveAtVelocity(self, *args)
    def moveToPosition(self, *args): return _wallaby.Motor_moveToPosition(self, *args)
    def moveRelativePosition(self, *args): return _wallaby.Motor_moveRelativePosition(self, *args)
    def freeze(self): return _wallaby.Motor_freeze(self)
    def isMotorDone(self): return _wallaby.Motor_isMotorDone(self)
    def blockMotorDone(self): return _wallaby.Motor_blockMotorDone(self)
    def forward(self): return _wallaby.Motor_forward(self)
    def backward(self): return _wallaby.Motor_backward(self)
    def motor(self, *args): return _wallaby.Motor_motor(self, *args)
    def baasbennaguui(self, *args): return _wallaby.Motor_baasbennaguui(self, *args)
    def motorPower(self, *args): return _wallaby.Motor_motorPower(self, *args)
    def off(self): return _wallaby.Motor_off(self)
    def port(self): return _wallaby.Motor_port(self)
    __swig_destroy__ = _wallaby.delete_Motor
    __del__ = lambda self : None;
Motor_swigregister = _wallaby.Motor_swigregister
Motor_swigregister(Motor)

class BackEMF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BackEMF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BackEMF, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_BackEMF(*args)
        try: self.this.append(this)
        except: self.this = this
    def value(self): return _wallaby.BackEMF_value(self)
    def port(self): return _wallaby.BackEMF_port(self)
    __swig_destroy__ = _wallaby.delete_BackEMF
    __del__ = lambda self : None;
BackEMF_swigregister = _wallaby.BackEMF_swigregister
BackEMF_swigregister(BackEMF)

class Servo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Servo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Servo, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Servo(*args)
        try: self.this.append(this)
        except: self.this = this
    def setPosition(self, *args): return _wallaby.Servo_setPosition(self, *args)
    def position(self): return _wallaby.Servo_position(self)
    def disable(self): return _wallaby.Servo_disable(self)
    def enable(self): return _wallaby.Servo_enable(self)
    def setEnabled(self, *args): return _wallaby.Servo_setEnabled(self, *args)
    def isEnabled(self): return _wallaby.Servo_isEnabled(self)
    __swig_destroy__ = _wallaby.delete_Servo
    __del__ = lambda self : None;
Servo_swigregister = _wallaby.Servo_swigregister
Servo_swigregister(Servo)

class Rgb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Rgb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Rgb, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _wallaby.Rgb_r_set
    __swig_getmethods__["r"] = _wallaby.Rgb_r_get
    if _newclass:r = _swig_property(_wallaby.Rgb_r_get, _wallaby.Rgb_r_set)
    __swig_setmethods__["g"] = _wallaby.Rgb_g_set
    __swig_getmethods__["g"] = _wallaby.Rgb_g_get
    if _newclass:g = _swig_property(_wallaby.Rgb_g_get, _wallaby.Rgb_g_set)
    __swig_setmethods__["b"] = _wallaby.Rgb_b_set
    __swig_getmethods__["b"] = _wallaby.Rgb_b_get
    if _newclass:b = _swig_property(_wallaby.Rgb_b_get, _wallaby.Rgb_b_set)
    def __init__(self): 
        this = _wallaby.new_Rgb()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Rgb
    __del__ = lambda self : None;
Rgb_swigregister = _wallaby.Rgb_swigregister
Rgb_swigregister(Rgb)

class Hsv(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Hsv, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Hsv, name)
    __repr__ = _swig_repr
    __swig_setmethods__["h"] = _wallaby.Hsv_h_set
    __swig_getmethods__["h"] = _wallaby.Hsv_h_get
    if _newclass:h = _swig_property(_wallaby.Hsv_h_get, _wallaby.Hsv_h_set)
    __swig_setmethods__["s"] = _wallaby.Hsv_s_set
    __swig_getmethods__["s"] = _wallaby.Hsv_s_get
    if _newclass:s = _swig_property(_wallaby.Hsv_s_get, _wallaby.Hsv_s_set)
    __swig_setmethods__["v"] = _wallaby.Hsv_v_set
    __swig_getmethods__["v"] = _wallaby.Hsv_v_get
    if _newclass:v = _swig_property(_wallaby.Hsv_v_get, _wallaby.Hsv_v_set)
    def __init__(self): 
        this = _wallaby.new_Hsv()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Hsv
    __del__ = lambda self : None;
Hsv_swigregister = _wallaby.Hsv_swigregister
Hsv_swigregister(Hsv)

class Battery(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Battery, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Battery, name)
    __repr__ = _swig_repr
    __swig_getmethods__["isCharging"] = lambda x: _wallaby.Battery_isCharging
    if _newclass:isCharging = staticmethod(_wallaby.Battery_isCharging)
    __swig_getmethods__["powerLevel"] = lambda x: _wallaby.Battery_powerLevel
    if _newclass:powerLevel = staticmethod(_wallaby.Battery_powerLevel)
    __swig_getmethods__["rawPowerADC"] = lambda x: _wallaby.Battery_rawPowerADC
    if _newclass:rawPowerADC = staticmethod(_wallaby.Battery_rawPowerADC)
    def __init__(self): 
        this = _wallaby.new_Battery()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Battery
    __del__ = lambda self : None;
Battery_swigregister = _wallaby.Battery_swigregister
Battery_swigregister(Battery)

def Battery_isCharging():
  return _wallaby.Battery_isCharging()
Battery_isCharging = _wallaby.Battery_isCharging

def Battery_powerLevel(battery_type=0):
  return _wallaby.Battery_powerLevel(battery_type)
Battery_powerLevel = _wallaby.Battery_powerLevel

def Battery_rawPowerADC():
  return _wallaby.Battery_rawPowerADC()
Battery_rawPowerADC = _wallaby.Battery_rawPowerADC

class Analog(UnsignedShortSensor):
    __swig_setmethods__ = {}
    for _s in [UnsignedShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Analog, name, value)
    __swig_getmethods__ = {}
    for _s in [UnsignedShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Analog, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Analog(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Analog
    __del__ = lambda self : None;
    def value(self): return _wallaby.Analog_value(self)
    def setPullup(self, *args): return _wallaby.Analog_setPullup(self, *args)
    def pullup(self): return _wallaby.Analog_pullup(self)
    def port(self): return _wallaby.Analog_port(self)
Analog_swigregister = _wallaby.Analog_swigregister
Analog_swigregister(Analog)

class Analog8(Analog):
    __swig_setmethods__ = {}
    for _s in [Analog]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Analog8, name, value)
    __swig_getmethods__ = {}
    for _s in [Analog]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Analog8, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Analog8(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Analog8
    __del__ = lambda self : None;
    def value(self): return _wallaby.Analog8_value(self)
Analog8_swigregister = _wallaby.Analog8_swigregister
Analog8_swigregister(Analog8)

class Analog10(Analog):
    __swig_setmethods__ = {}
    for _s in [Analog]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Analog10, name, value)
    __swig_getmethods__ = {}
    for _s in [Analog]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Analog10, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Analog10(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Analog10
    __del__ = lambda self : None;
    def value(self): return _wallaby.Analog10_value(self)
Analog10_swigregister = _wallaby.Analog10_swigregister
Analog10_swigregister(Analog10)

class Acceleration(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Acceleration, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Acceleration, name)
    __repr__ = _swig_repr
    __swig_getmethods__["x"] = lambda x: _wallaby.Acceleration_x
    if _newclass:x = staticmethod(_wallaby.Acceleration_x)
    __swig_getmethods__["y"] = lambda x: _wallaby.Acceleration_y
    if _newclass:y = staticmethod(_wallaby.Acceleration_y)
    __swig_getmethods__["z"] = lambda x: _wallaby.Acceleration_z
    if _newclass:z = staticmethod(_wallaby.Acceleration_z)
    __swig_getmethods__["calibrate"] = lambda x: _wallaby.Acceleration_calibrate
    if _newclass:calibrate = staticmethod(_wallaby.Acceleration_calibrate)
    def __init__(self): 
        this = _wallaby.new_Acceleration()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Acceleration
    __del__ = lambda self : None;
Acceleration_swigregister = _wallaby.Acceleration_swigregister
Acceleration_swigregister(Acceleration)

def Acceleration_x():
  return _wallaby.Acceleration_x()
Acceleration_x = _wallaby.Acceleration_x

def Acceleration_y():
  return _wallaby.Acceleration_y()
Acceleration_y = _wallaby.Acceleration_y

def Acceleration_z():
  return _wallaby.Acceleration_z()
Acceleration_z = _wallaby.Acceleration_z

def Acceleration_calibrate():
  return _wallaby.Acceleration_calibrate()
Acceleration_calibrate = _wallaby.Acceleration_calibrate

class AccelX(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AccelX, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AccelX, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.AccelX_value(self)
    def __init__(self): 
        this = _wallaby.new_AccelX()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_AccelX
    __del__ = lambda self : None;
AccelX_swigregister = _wallaby.AccelX_swigregister
AccelX_swigregister(AccelX)

class AccelY(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AccelY, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AccelY, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.AccelY_value(self)
    def __init__(self): 
        this = _wallaby.new_AccelY()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_AccelY
    __del__ = lambda self : None;
AccelY_swigregister = _wallaby.AccelY_swigregister
AccelY_swigregister(AccelY)

class AccelZ(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AccelZ, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AccelZ, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.AccelZ_value(self)
    def __init__(self): 
        this = _wallaby.new_AccelZ()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_AccelZ
    __del__ = lambda self : None;
AccelZ_swigregister = _wallaby.AccelZ_swigregister
AccelZ_swigregister(AccelZ)

class Compass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Compass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Compass, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _wallaby.new_Compass()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Compass
    __del__ = lambda self : None;
    __swig_getmethods__["calibrate"] = lambda x: _wallaby.Compass_calibrate
    if _newclass:calibrate = staticmethod(_wallaby.Compass_calibrate)
    __swig_getmethods__["setParams"] = lambda x: _wallaby.Compass_setParams
    if _newclass:setParams = staticmethod(_wallaby.Compass_setParams)
    __swig_getmethods__["getAngle"] = lambda x: _wallaby.Compass_getAngle
    if _newclass:getAngle = staticmethod(_wallaby.Compass_getAngle)
Compass_swigregister = _wallaby.Compass_swigregister
Compass_swigregister(Compass)

def Compass_calibrate():
  return _wallaby.Compass_calibrate()
Compass_calibrate = _wallaby.Compass_calibrate

def Compass_setParams(*args):
  return _wallaby.Compass_setParams(*args)
Compass_setParams = _wallaby.Compass_setParams

def Compass_getAngle():
  return _wallaby.Compass_getAngle()
Compass_getAngle = _wallaby.Compass_getAngle

class Gyro(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Gyro, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Gyro, name)
    __repr__ = _swig_repr
    __swig_getmethods__["x"] = lambda x: _wallaby.Gyro_x
    if _newclass:x = staticmethod(_wallaby.Gyro_x)
    __swig_getmethods__["y"] = lambda x: _wallaby.Gyro_y
    if _newclass:y = staticmethod(_wallaby.Gyro_y)
    __swig_getmethods__["z"] = lambda x: _wallaby.Gyro_z
    if _newclass:z = staticmethod(_wallaby.Gyro_z)
    __swig_getmethods__["calibrate"] = lambda x: _wallaby.Gyro_calibrate
    if _newclass:calibrate = staticmethod(_wallaby.Gyro_calibrate)
    def __init__(self): 
        this = _wallaby.new_Gyro()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Gyro
    __del__ = lambda self : None;
Gyro_swigregister = _wallaby.Gyro_swigregister
Gyro_swigregister(Gyro)

def Gyro_x():
  return _wallaby.Gyro_x()
Gyro_x = _wallaby.Gyro_x

def Gyro_y():
  return _wallaby.Gyro_y()
Gyro_y = _wallaby.Gyro_y

def Gyro_z():
  return _wallaby.Gyro_z()
Gyro_z = _wallaby.Gyro_z

def Gyro_calibrate():
  return _wallaby.Gyro_calibrate()
Gyro_calibrate = _wallaby.Gyro_calibrate

class GyroX(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GyroX, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GyroX, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.GyroX_value(self)
    def __init__(self): 
        this = _wallaby.new_GyroX()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_GyroX
    __del__ = lambda self : None;
GyroX_swigregister = _wallaby.GyroX_swigregister
GyroX_swigregister(GyroX)

class GyroY(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GyroY, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GyroY, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.GyroY_value(self)
    def __init__(self): 
        this = _wallaby.new_GyroY()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_GyroY
    __del__ = lambda self : None;
GyroY_swigregister = _wallaby.GyroY_swigregister
GyroY_swigregister(GyroY)

class GyroZ(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GyroZ, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GyroZ, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.GyroZ_value(self)
    def __init__(self): 
        this = _wallaby.new_GyroZ()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_GyroZ
    __del__ = lambda self : None;
GyroZ_swigregister = _wallaby.GyroZ_swigregister
GyroZ_swigregister(GyroZ)

class Magneto(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Magneto, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Magneto, name)
    __repr__ = _swig_repr
    __swig_getmethods__["x"] = lambda x: _wallaby.Magneto_x
    if _newclass:x = staticmethod(_wallaby.Magneto_x)
    __swig_getmethods__["y"] = lambda x: _wallaby.Magneto_y
    if _newclass:y = staticmethod(_wallaby.Magneto_y)
    __swig_getmethods__["z"] = lambda x: _wallaby.Magneto_z
    if _newclass:z = staticmethod(_wallaby.Magneto_z)
    __swig_getmethods__["calibrate"] = lambda x: _wallaby.Magneto_calibrate
    if _newclass:calibrate = staticmethod(_wallaby.Magneto_calibrate)
    def __init__(self): 
        this = _wallaby.new_Magneto()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Magneto
    __del__ = lambda self : None;
Magneto_swigregister = _wallaby.Magneto_swigregister
Magneto_swigregister(Magneto)

def Magneto_x():
  return _wallaby.Magneto_x()
Magneto_x = _wallaby.Magneto_x

def Magneto_y():
  return _wallaby.Magneto_y()
Magneto_y = _wallaby.Magneto_y

def Magneto_z():
  return _wallaby.Magneto_z()
Magneto_z = _wallaby.Magneto_z

def Magneto_calibrate():
  return _wallaby.Magneto_calibrate()
Magneto_calibrate = _wallaby.Magneto_calibrate

class MagnetoX(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MagnetoX, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MagnetoX, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.MagnetoX_value(self)
    def __init__(self): 
        this = _wallaby.new_MagnetoX()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_MagnetoX
    __del__ = lambda self : None;
MagnetoX_swigregister = _wallaby.MagnetoX_swigregister
MagnetoX_swigregister(MagnetoX)

class MagnetoY(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MagnetoY, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MagnetoY, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.MagnetoY_value(self)
    def __init__(self): 
        this = _wallaby.new_MagnetoY()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_MagnetoY
    __del__ = lambda self : None;
MagnetoY_swigregister = _wallaby.MagnetoY_swigregister
MagnetoY_swigregister(MagnetoY)

class MagnetoZ(ShortSensor):
    __swig_setmethods__ = {}
    for _s in [ShortSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MagnetoZ, name, value)
    __swig_getmethods__ = {}
    for _s in [ShortSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MagnetoZ, name)
    __repr__ = _swig_repr
    def value(self): return _wallaby.MagnetoZ_value(self)
    def __init__(self): 
        this = _wallaby.new_MagnetoZ()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_MagnetoZ
    __del__ = lambda self : None;
MagnetoZ_swigregister = _wallaby.MagnetoZ_swigregister
MagnetoZ_swigregister(MagnetoZ)

class AbstractButton(BoolSensor):
    __swig_setmethods__ = {}
    for _s in [BoolSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AbstractButton, name, value)
    __swig_getmethods__ = {}
    for _s in [BoolSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AbstractButton, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_AbstractButton
    __del__ = lambda self : None;
    def setPressed(self, *args): return _wallaby.AbstractButton_setPressed(self, *args)
    def isPressed(self): return _wallaby.AbstractButton_isPressed(self)
    def isNotPressed(self): return _wallaby.AbstractButton_isNotPressed(self)
    def isClicked(self): return _wallaby.AbstractButton_isClicked(self)
    def waitUntilReleased(self): return _wallaby.AbstractButton_waitUntilReleased(self)
    def waitUntilPressed(self): return _wallaby.AbstractButton_waitUntilPressed(self)
    def waitUntilClicked(self): return _wallaby.AbstractButton_waitUntilClicked(self)
AbstractButton_swigregister = _wallaby.AbstractButton_swigregister
AbstractButton_swigregister(AbstractButton)

class AbstractTextButton(AbstractButton):
    __swig_setmethods__ = {}
    for _s in [AbstractButton]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AbstractTextButton, name, value)
    __swig_getmethods__ = {}
    for _s in [AbstractButton]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AbstractTextButton, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_AbstractTextButton
    __del__ = lambda self : None;
    def setText(self, *args): return _wallaby.AbstractTextButton_setText(self, *args)
    def text(self): return _wallaby.AbstractTextButton_text(self)
    def isTextDirty(self): return _wallaby.AbstractTextButton_isTextDirty(self)
    def resetText(self): return _wallaby.AbstractTextButton_resetText(self)
AbstractTextButton_swigregister = _wallaby.AbstractTextButton_swigregister
AbstractTextButton_swigregister(AbstractTextButton)

class IdButton(AbstractTextButton):
    __swig_setmethods__ = {}
    for _s in [AbstractTextButton]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, IdButton, name, value)
    __swig_getmethods__ = {}
    for _s in [AbstractTextButton]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, IdButton, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_IdButton(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_IdButton
    __del__ = lambda self : None;
    def setText(self, *args): return _wallaby.IdButton_setText(self, *args)
    def text(self): return _wallaby.IdButton_text(self)
    def isTextDirty(self): return _wallaby.IdButton_isTextDirty(self)
    def setPressed(self, *args): return _wallaby.IdButton_setPressed(self, *args)
    def value(self): return _wallaby.IdButton_value(self)
    def resetText(self): return _wallaby.IdButton_resetText(self)
IdButton_swigregister = _wallaby.IdButton_swigregister
IdButton_swigregister(IdButton)

class ExtraButtons(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ExtraButtons, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ExtraButtons, name)
    __repr__ = _swig_repr
    __swig_getmethods__["show"] = lambda x: _wallaby.ExtraButtons_show
    if _newclass:show = staticmethod(_wallaby.ExtraButtons_show)
    __swig_getmethods__["hide"] = lambda x: _wallaby.ExtraButtons_hide
    if _newclass:hide = staticmethod(_wallaby.ExtraButtons_hide)
    __swig_getmethods__["setShown"] = lambda x: _wallaby.ExtraButtons_setShown
    if _newclass:setShown = staticmethod(_wallaby.ExtraButtons_setShown)
    __swig_getmethods__["isShown"] = lambda x: _wallaby.ExtraButtons_isShown
    if _newclass:isShown = staticmethod(_wallaby.ExtraButtons_isShown)
    def __init__(self): 
        this = _wallaby.new_ExtraButtons()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_ExtraButtons
    __del__ = lambda self : None;
ExtraButtons_swigregister = _wallaby.ExtraButtons_swigregister
ExtraButtons_swigregister(ExtraButtons)

def ExtraButtons_show():
  return _wallaby.ExtraButtons_show()
ExtraButtons_show = _wallaby.ExtraButtons_show

def ExtraButtons_hide():
  return _wallaby.ExtraButtons_hide()
ExtraButtons_hide = _wallaby.ExtraButtons_hide

def ExtraButtons_setShown(*args):
  return _wallaby.ExtraButtons_setShown(*args)
ExtraButtons_setShown = _wallaby.ExtraButtons_setShown

def ExtraButtons_isShown():
  return _wallaby.ExtraButtons_isShown()
ExtraButtons_isShown = _wallaby.ExtraButtons_isShown

class Config(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Config, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Config, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Config(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_getmethods__["load"] = lambda x: _wallaby.Config_load
    if _newclass:load = staticmethod(_wallaby.Config_load)
    def save(self, *args): return _wallaby.Config_save(self, *args)
    def beginGroup(self, *args): return _wallaby.Config_beginGroup(self, *args)
    def endGroup(self): return _wallaby.Config_endGroup(self)
    def clearGroup(self): return _wallaby.Config_clearGroup(self)
    def clear(self): return _wallaby.Config_clear(self)
    def containsKey(self, *args): return _wallaby.Config_containsKey(self, *args)
    def boolValue(self, *args): return _wallaby.Config_boolValue(self, *args)
    def intValue(self, *args): return _wallaby.Config_intValue(self, *args)
    def doubleValue(self, *args): return _wallaby.Config_doubleValue(self, *args)
    def stringValue(self, *args): return _wallaby.Config_stringValue(self, *args)
    def setValue(self, *args): return _wallaby.Config_setValue(self, *args)
    def values(self): return _wallaby.Config_values(self)
    def addValues(self, *args): return _wallaby.Config_addValues(self, *args)
    __swig_destroy__ = _wallaby.delete_Config
    __del__ = lambda self : None;
Config_swigregister = _wallaby.Config_swigregister
Config_swigregister(Config)
cvar = _wallaby.cvar
all = cvar.all

def Config_load(*args):
  return _wallaby.Config_load(*args)
Config_load = _wallaby.Config_load

class Digital(BoolSensor):
    __swig_setmethods__ = {}
    for _s in [BoolSensor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Digital, name, value)
    __swig_getmethods__ = {}
    for _s in [BoolSensor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Digital, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wallaby.new_Digital(*args)
        try: self.this.append(this)
        except: self.this = this
    def setValue(self, *args): return _wallaby.Digital_setValue(self, *args)
    def setOutput(self, *args): return _wallaby.Digital_setOutput(self, *args)
    def isOutput(self): return _wallaby.Digital_isOutput(self)
    def setPullup(self, *args): return _wallaby.Digital_setPullup(self, *args)
    def pullup(self): return _wallaby.Digital_pullup(self)
    def value(self): return _wallaby.Digital_value(self)
    __swig_destroy__ = _wallaby.delete_Digital
    __del__ = lambda self : None;
Digital_swigregister = _wallaby.Digital_swigregister
Digital_swigregister(Digital)


def graphics_open(*args):
  return _wallaby.graphics_open(*args)
graphics_open = _wallaby.graphics_open

def graphics_close():
  return _wallaby.graphics_close()
graphics_close = _wallaby.graphics_close

def graphics_update():
  return _wallaby.graphics_update()
graphics_update = _wallaby.graphics_update

def graphics_clear():
  return _wallaby.graphics_clear()
graphics_clear = _wallaby.graphics_clear
RGB = _wallaby.RGB
BGR = _wallaby.BGR

def graphics_blit(*args):
  return _wallaby.graphics_blit(*args)
graphics_blit = _wallaby.graphics_blit

def graphics_blit_region(*args):
  return _wallaby.graphics_blit_region(*args)
graphics_blit_region = _wallaby.graphics_blit_region

def graphics_blit_enc(*args):
  return _wallaby.graphics_blit_enc(*args)
graphics_blit_enc = _wallaby.graphics_blit_enc

def graphics_blit_region_enc(*args):
  return _wallaby.graphics_blit_region_enc(*args)
graphics_blit_region_enc = _wallaby.graphics_blit_region_enc

def graphics_fill(*args):
  return _wallaby.graphics_fill(*args)
graphics_fill = _wallaby.graphics_fill

def graphics_pixel(*args):
  return _wallaby.graphics_pixel(*args)
graphics_pixel = _wallaby.graphics_pixel

def graphics_line(*args):
  return _wallaby.graphics_line(*args)
graphics_line = _wallaby.graphics_line

def graphics_circle(*args):
  return _wallaby.graphics_circle(*args)
graphics_circle = _wallaby.graphics_circle

def graphics_circle_fill(*args):
  return _wallaby.graphics_circle_fill(*args)
graphics_circle_fill = _wallaby.graphics_circle_fill

def graphics_rectangle(*args):
  return _wallaby.graphics_rectangle(*args)
graphics_rectangle = _wallaby.graphics_rectangle

def graphics_rectangle_fill(*args):
  return _wallaby.graphics_rectangle_fill(*args)
graphics_rectangle_fill = _wallaby.graphics_rectangle_fill

def graphics_triangle(*args):
  return _wallaby.graphics_triangle(*args)
graphics_triangle = _wallaby.graphics_triangle

def graphics_triangle_fill(*args):
  return _wallaby.graphics_triangle_fill(*args)
graphics_triangle_fill = _wallaby.graphics_triangle_fill

def get_key_state(*args):
  return _wallaby.get_key_state(*args)
get_key_state = _wallaby.get_key_state

def get_mouse_position(*args):
  return _wallaby.get_mouse_position(*args)
get_mouse_position = _wallaby.get_mouse_position

def get_mouse_middle_button():
  return _wallaby.get_mouse_middle_button()
get_mouse_middle_button = _wallaby.get_mouse_middle_button

def get_mouse_left_button():
  return _wallaby.get_mouse_left_button()
get_mouse_left_button = _wallaby.get_mouse_left_button

def get_mouse_right_button():
  return _wallaby.get_mouse_right_button()
get_mouse_right_button = _wallaby.get_mouse_right_button
class Mutex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mutex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mutex, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _wallaby.new_Mutex()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_Mutex
    __del__ = lambda self : None;
    def lock(self): return _wallaby.Mutex_lock(self)
    def tryLock(self): return _wallaby.Mutex_tryLock(self)
    def unlock(self): return _wallaby.Mutex_unlock(self)
Mutex_swigregister = _wallaby.Mutex_swigregister
Mutex_swigregister(Mutex)

class Thread(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Thread, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Thread, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wallaby.delete_Thread
    __del__ = lambda self : None;
    def start(self): return _wallaby.Thread_start(self)
    def join(self): return _wallaby.Thread_join(self)
    def run(self): return _wallaby.Thread_run(self)
Thread_swigregister = _wallaby.Thread_swigregister
Thread_swigregister(Thread)


def get_motor_position_counter(*args):
  return _wallaby.get_motor_position_counter(*args)
get_motor_position_counter = _wallaby.get_motor_position_counter

def gmpc(*args):
  return _wallaby.gmpc(*args)
gmpc = _wallaby.gmpc

def clear_motor_position_counter(*args):
  return _wallaby.clear_motor_position_counter(*args)
clear_motor_position_counter = _wallaby.clear_motor_position_counter

def cmpc(*args):
  return _wallaby.cmpc(*args)
cmpc = _wallaby.cmpc

def move_at_velocity(*args):
  return _wallaby.move_at_velocity(*args)
move_at_velocity = _wallaby.move_at_velocity

def mav(*args):
  return _wallaby.mav(*args)
mav = _wallaby.mav

def move_to_position(*args):
  return _wallaby.move_to_position(*args)
move_to_position = _wallaby.move_to_position

def mtp(*args):
  return _wallaby.mtp(*args)
mtp = _wallaby.mtp

def move_relative_position(*args):
  return _wallaby.move_relative_position(*args)
move_relative_position = _wallaby.move_relative_position

def mrp(*args):
  return _wallaby.mrp(*args)
mrp = _wallaby.mrp

def set_pid_gains(*args):
  return _wallaby.set_pid_gains(*args)
set_pid_gains = _wallaby.set_pid_gains

def get_pid_gains(*args):
  return _wallaby.get_pid_gains(*args)
get_pid_gains = _wallaby.get_pid_gains

def freeze(*args):
  return _wallaby.freeze(*args)
freeze = _wallaby.freeze

def get_motor_done(*args):
  return _wallaby.get_motor_done(*args)
get_motor_done = _wallaby.get_motor_done

def block_motor_done(*args):
  return _wallaby.block_motor_done(*args)
block_motor_done = _wallaby.block_motor_done

def bmd(*args):
  return _wallaby.bmd(*args)
bmd = _wallaby.bmd

def setpwm(*args):
  return _wallaby.setpwm(*args)
setpwm = _wallaby.setpwm

def getpwm(*args):
  return _wallaby.getpwm(*args)
getpwm = _wallaby.getpwm

def fd(*args):
  return _wallaby.fd(*args)
fd = _wallaby.fd

def bk(*args):
  return _wallaby.bk(*args)
bk = _wallaby.bk

def motor(*args):
  return _wallaby.motor(*args)
motor = _wallaby.motor

def baasbennaguui(*args):
  return _wallaby.baasbennaguui(*args)
baasbennaguui = _wallaby.baasbennaguui

def motor_power(*args):
  return _wallaby.motor_power(*args)
motor_power = _wallaby.motor_power

def off(*args):
  return _wallaby.off(*args)
off = _wallaby.off

def alloff():
  return _wallaby.alloff()
alloff = _wallaby.alloff

def ao():
  return _wallaby.ao()
ao = _wallaby.ao
class point2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point2, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _wallaby.point2_x_set
    __swig_getmethods__["x"] = _wallaby.point2_x_get
    if _newclass:x = _swig_property(_wallaby.point2_x_get, _wallaby.point2_x_set)
    __swig_setmethods__["y"] = _wallaby.point2_y_set
    __swig_getmethods__["y"] = _wallaby.point2_y_get
    if _newclass:y = _swig_property(_wallaby.point2_y_get, _wallaby.point2_y_set)
    def __init__(self): 
        this = _wallaby.new_point2()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_point2
    __del__ = lambda self : None;
point2_swigregister = _wallaby.point2_swigregister
point2_swigregister(point2)

class point3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _wallaby.point3_x_set
    __swig_getmethods__["x"] = _wallaby.point3_x_get
    if _newclass:x = _swig_property(_wallaby.point3_x_get, _wallaby.point3_x_set)
    __swig_setmethods__["y"] = _wallaby.point3_y_set
    __swig_getmethods__["y"] = _wallaby.point3_y_get
    if _newclass:y = _swig_property(_wallaby.point3_y_get, _wallaby.point3_y_set)
    __swig_setmethods__["z"] = _wallaby.point3_z_set
    __swig_getmethods__["z"] = _wallaby.point3_z_get
    if _newclass:z = _swig_property(_wallaby.point3_z_get, _wallaby.point3_z_set)
    def __init__(self): 
        this = _wallaby.new_point3()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_point3
    __del__ = lambda self : None;
point3_swigregister = _wallaby.point3_swigregister
point3_swigregister(point3)

class rectangle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rectangle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rectangle, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ulx"] = _wallaby.rectangle_ulx_set
    __swig_getmethods__["ulx"] = _wallaby.rectangle_ulx_get
    if _newclass:ulx = _swig_property(_wallaby.rectangle_ulx_get, _wallaby.rectangle_ulx_set)
    __swig_setmethods__["uly"] = _wallaby.rectangle_uly_set
    __swig_getmethods__["uly"] = _wallaby.rectangle_uly_get
    if _newclass:uly = _swig_property(_wallaby.rectangle_uly_get, _wallaby.rectangle_uly_set)
    __swig_setmethods__["width"] = _wallaby.rectangle_width_set
    __swig_getmethods__["width"] = _wallaby.rectangle_width_get
    if _newclass:width = _swig_property(_wallaby.rectangle_width_get, _wallaby.rectangle_width_set)
    __swig_setmethods__["height"] = _wallaby.rectangle_height_set
    __swig_getmethods__["height"] = _wallaby.rectangle_height_get
    if _newclass:height = _swig_property(_wallaby.rectangle_height_get, _wallaby.rectangle_height_set)
    def __init__(self): 
        this = _wallaby.new_rectangle()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_rectangle
    __del__ = lambda self : None;
rectangle_swigregister = _wallaby.rectangle_swigregister
rectangle_swigregister(rectangle)


def create_point2(*args):
  return _wallaby.create_point2(*args)
create_point2 = _wallaby.create_point2

def create_point3(*args):
  return _wallaby.create_point3(*args)
create_point3 = _wallaby.create_point3

def create_rectangle(*args):
  return _wallaby.create_rectangle(*args)
create_rectangle = _wallaby.create_rectangle

def enable_servo(*args):
  return _wallaby.enable_servo(*args)
enable_servo = _wallaby.enable_servo

def disable_servo(*args):
  return _wallaby.disable_servo(*args)
disable_servo = _wallaby.disable_servo

def enable_servos():
  return _wallaby.enable_servos()
enable_servos = _wallaby.enable_servos

def disable_servos():
  return _wallaby.disable_servos()
disable_servos = _wallaby.disable_servos

def set_servo_enabled(*args):
  return _wallaby.set_servo_enabled(*args)
set_servo_enabled = _wallaby.set_servo_enabled

def get_servo_enabled(*args):
  return _wallaby.get_servo_enabled(*args)
get_servo_enabled = _wallaby.get_servo_enabled

def get_servo_position(*args):
  return _wallaby.get_servo_position(*args)
get_servo_position = _wallaby.get_servo_position

def set_servo_position(*args):
  return _wallaby.set_servo_position(*args)
set_servo_position = _wallaby.set_servo_position

def msleep(*args):
  return _wallaby.msleep(*args)
msleep = _wallaby.msleep

def iitxash(*args):
  return _wallaby.iitxash(*args)
iitxash = _wallaby.iitxash

def systime():
  return _wallaby.systime()
systime = _wallaby.systime

def seconds():
  return _wallaby.seconds()
seconds = _wallaby.seconds

def create_connect():
  return _wallaby.create_connect()
create_connect = _wallaby.create_connect

def create_connect_once():
  return _wallaby.create_connect_once()
create_connect_once = _wallaby.create_connect_once

def create_disconnect():
  return _wallaby.create_disconnect()
create_disconnect = _wallaby.create_disconnect

def create_start():
  return _wallaby.create_start()
create_start = _wallaby.create_start

def create_passive():
  return _wallaby.create_passive()
create_passive = _wallaby.create_passive

def create_safe():
  return _wallaby.create_safe()
create_safe = _wallaby.create_safe

def create_full():
  return _wallaby.create_full()
create_full = _wallaby.create_full

def create_spot():
  return _wallaby.create_spot()
create_spot = _wallaby.create_spot

def create_cover():
  return _wallaby.create_cover()
create_cover = _wallaby.create_cover

def create_demo(*args):
  return _wallaby.create_demo(*args)
create_demo = _wallaby.create_demo

def create_cover_dock():
  return _wallaby.create_cover_dock()
create_cover_dock = _wallaby.create_cover_dock

def get_create_mode():
  return _wallaby.get_create_mode()
get_create_mode = _wallaby.get_create_mode

def get_create_lbump():
  return _wallaby.get_create_lbump()
get_create_lbump = _wallaby.get_create_lbump

def get_create_rbump():
  return _wallaby.get_create_rbump()
get_create_rbump = _wallaby.get_create_rbump

def get_create_lwdrop():
  return _wallaby.get_create_lwdrop()
get_create_lwdrop = _wallaby.get_create_lwdrop

def get_create_cwdrop():
  return _wallaby.get_create_cwdrop()
get_create_cwdrop = _wallaby.get_create_cwdrop

def get_create_rwdrop():
  return _wallaby.get_create_rwdrop()
get_create_rwdrop = _wallaby.get_create_rwdrop

def get_create_wall():
  return _wallaby.get_create_wall()
get_create_wall = _wallaby.get_create_wall

def get_create_lcliff():
  return _wallaby.get_create_lcliff()
get_create_lcliff = _wallaby.get_create_lcliff

def get_create_lfcliff():
  return _wallaby.get_create_lfcliff()
get_create_lfcliff = _wallaby.get_create_lfcliff

def get_create_rfcliff():
  return _wallaby.get_create_rfcliff()
get_create_rfcliff = _wallaby.get_create_rfcliff

def get_create_rcliff():
  return _wallaby.get_create_rcliff()
get_create_rcliff = _wallaby.get_create_rcliff

def get_create_llightbump():
  return _wallaby.get_create_llightbump()
get_create_llightbump = _wallaby.get_create_llightbump

def get_create_lflightbump():
  return _wallaby.get_create_lflightbump()
get_create_lflightbump = _wallaby.get_create_lflightbump

def get_create_lclightbump():
  return _wallaby.get_create_lclightbump()
get_create_lclightbump = _wallaby.get_create_lclightbump

def get_create_rclightbump():
  return _wallaby.get_create_rclightbump()
get_create_rclightbump = _wallaby.get_create_rclightbump

def get_create_rflightbump():
  return _wallaby.get_create_rflightbump()
get_create_rflightbump = _wallaby.get_create_rflightbump

def get_create_rlightbump():
  return _wallaby.get_create_rlightbump()
get_create_rlightbump = _wallaby.get_create_rlightbump

def get_create_llightbump_amt():
  return _wallaby.get_create_llightbump_amt()
get_create_llightbump_amt = _wallaby.get_create_llightbump_amt

def get_create_rlightbump_amt():
  return _wallaby.get_create_rlightbump_amt()
get_create_rlightbump_amt = _wallaby.get_create_rlightbump_amt

def get_create_lflightbump_amt():
  return _wallaby.get_create_lflightbump_amt()
get_create_lflightbump_amt = _wallaby.get_create_lflightbump_amt

def get_create_lclightbump_amt():
  return _wallaby.get_create_lclightbump_amt()
get_create_lclightbump_amt = _wallaby.get_create_lclightbump_amt

def get_create_rclightbump_amt():
  return _wallaby.get_create_rclightbump_amt()
get_create_rclightbump_amt = _wallaby.get_create_rclightbump_amt

def get_create_rflightbump_amt():
  return _wallaby.get_create_rflightbump_amt()
get_create_rflightbump_amt = _wallaby.get_create_rflightbump_amt

def get_create_vwall():
  return _wallaby.get_create_vwall()
get_create_vwall = _wallaby.get_create_vwall

def get_create_overcurrents():
  return _wallaby.get_create_overcurrents()
get_create_overcurrents = _wallaby.get_create_overcurrents

def get_create_infrared():
  return _wallaby.get_create_infrared()
get_create_infrared = _wallaby.get_create_infrared

def get_create_advance_button():
  return _wallaby.get_create_advance_button()
get_create_advance_button = _wallaby.get_create_advance_button

def get_create_play_button():
  return _wallaby.get_create_play_button()
get_create_play_button = _wallaby.get_create_play_button

def get_create_normalized_angle():
  return _wallaby.get_create_normalized_angle()
get_create_normalized_angle = _wallaby.get_create_normalized_angle

def set_create_normalized_angle(*args):
  return _wallaby.set_create_normalized_angle(*args)
set_create_normalized_angle = _wallaby.set_create_normalized_angle

def get_create_total_angle():
  return _wallaby.get_create_total_angle()
get_create_total_angle = _wallaby.get_create_total_angle

def set_create_total_angle(*args):
  return _wallaby.set_create_total_angle(*args)
set_create_total_angle = _wallaby.set_create_total_angle

def get_create_distance():
  return _wallaby.get_create_distance()
get_create_distance = _wallaby.get_create_distance

def set_create_distance(*args):
  return _wallaby.set_create_distance(*args)
set_create_distance = _wallaby.set_create_distance

def get_create_battery_charging_state():
  return _wallaby.get_create_battery_charging_state()
get_create_battery_charging_state = _wallaby.get_create_battery_charging_state

def get_create_battery_voltage():
  return _wallaby.get_create_battery_voltage()
get_create_battery_voltage = _wallaby.get_create_battery_voltage

def get_create_battery_current():
  return _wallaby.get_create_battery_current()
get_create_battery_current = _wallaby.get_create_battery_current

def get_create_battery_temp():
  return _wallaby.get_create_battery_temp()
get_create_battery_temp = _wallaby.get_create_battery_temp

def get_create_battery_charge():
  return _wallaby.get_create_battery_charge()
get_create_battery_charge = _wallaby.get_create_battery_charge

def get_create_battery_capacity():
  return _wallaby.get_create_battery_capacity()
get_create_battery_capacity = _wallaby.get_create_battery_capacity

def get_create_wall_amt():
  return _wallaby.get_create_wall_amt()
get_create_wall_amt = _wallaby.get_create_wall_amt

def get_create_lcliff_amt():
  return _wallaby.get_create_lcliff_amt()
get_create_lcliff_amt = _wallaby.get_create_lcliff_amt

def get_create_lfcliff_amt():
  return _wallaby.get_create_lfcliff_amt()
get_create_lfcliff_amt = _wallaby.get_create_lfcliff_amt

def get_create_rfcliff_amt():
  return _wallaby.get_create_rfcliff_amt()
get_create_rfcliff_amt = _wallaby.get_create_rfcliff_amt

def get_create_rcliff_amt():
  return _wallaby.get_create_rcliff_amt()
get_create_rcliff_amt = _wallaby.get_create_rcliff_amt

def get_create_bay_DI():
  return _wallaby.get_create_bay_DI()
get_create_bay_DI = _wallaby.get_create_bay_DI

def get_create_bay_AI():
  return _wallaby.get_create_bay_AI()
get_create_bay_AI = _wallaby.get_create_bay_AI

def get_create_song_number():
  return _wallaby.get_create_song_number()
get_create_song_number = _wallaby.get_create_song_number

def get_create_song_playing():
  return _wallaby.get_create_song_playing()
get_create_song_playing = _wallaby.get_create_song_playing

def get_create_number_of_stream_packets():
  return _wallaby.get_create_number_of_stream_packets()
get_create_number_of_stream_packets = _wallaby.get_create_number_of_stream_packets

def get_create_requested_velocity():
  return _wallaby.get_create_requested_velocity()
get_create_requested_velocity = _wallaby.get_create_requested_velocity

def get_create_requested_radius():
  return _wallaby.get_create_requested_radius()
get_create_requested_radius = _wallaby.get_create_requested_radius

def get_create_requested_right_velocity():
  return _wallaby.get_create_requested_right_velocity()
get_create_requested_right_velocity = _wallaby.get_create_requested_right_velocity

def get_create_requested_left_velocity():
  return _wallaby.get_create_requested_left_velocity()
get_create_requested_left_velocity = _wallaby.get_create_requested_left_velocity

def create_stop():
  return _wallaby.create_stop()
create_stop = _wallaby.create_stop

def create_drive(*args):
  return _wallaby.create_drive(*args)
create_drive = _wallaby.create_drive

def create_drive_straight(*args):
  return _wallaby.create_drive_straight(*args)
create_drive_straight = _wallaby.create_drive_straight

def create_spin_CW(*args):
  return _wallaby.create_spin_CW(*args)
create_spin_CW = _wallaby.create_spin_CW

def create_spin_CCW(*args):
  return _wallaby.create_spin_CCW(*args)
create_spin_CCW = _wallaby.create_spin_CCW

def create_drive_direct(*args):
  return _wallaby.create_drive_direct(*args)
create_drive_direct = _wallaby.create_drive_direct

def create_spin_block(*args):
  return _wallaby.create_spin_block(*args)
create_spin_block = _wallaby.create_spin_block

def _create_get_raw_encoders(*args):
  return _wallaby._create_get_raw_encoders(*args)
_create_get_raw_encoders = _wallaby._create_get_raw_encoders

def create_advance_led(*args):
  return _wallaby.create_advance_led(*args)
create_advance_led = _wallaby.create_advance_led

def create_play_led(*args):
  return _wallaby.create_play_led(*args)
create_play_led = _wallaby.create_play_led

def create_power_led(*args):
  return _wallaby.create_power_led(*args)
create_power_led = _wallaby.create_power_led

def create_digital_output(*args):
  return _wallaby.create_digital_output(*args)
create_digital_output = _wallaby.create_digital_output

def create_pwm_low_side_drivers(*args):
  return _wallaby.create_pwm_low_side_drivers(*args)
create_pwm_low_side_drivers = _wallaby.create_pwm_low_side_drivers

def create_low_side_drivers(*args):
  return _wallaby.create_low_side_drivers(*args)
create_low_side_drivers = _wallaby.create_low_side_drivers

def create_load_song(*args):
  return _wallaby.create_load_song(*args)
create_load_song = _wallaby.create_load_song

def create_play_song(*args):
  return _wallaby.create_play_song(*args)
create_play_song = _wallaby.create_play_song

def create_read_block(*args):
  return _wallaby.create_read_block(*args)
create_read_block = _wallaby.create_read_block

def create_write_byte(*args):
  return _wallaby.create_write_byte(*args)
create_write_byte = _wallaby.create_write_byte

def create_clear_serial_buffer():
  return _wallaby.create_clear_serial_buffer()
create_clear_serial_buffer = _wallaby.create_clear_serial_buffer
Baud57600 = _wallaby.Baud57600
Baud115200 = _wallaby.Baud115200

def get_create_baud_rate():
  return _wallaby.get_create_baud_rate()
get_create_baud_rate = _wallaby.get_create_baud_rate

def set_create_baud_rate(*args):
  return _wallaby.set_create_baud_rate(*args)
set_create_baud_rate = _wallaby.set_create_baud_rate

def battery_charging():
  return _wallaby.battery_charging()
battery_charging = _wallaby.battery_charging

def power_level():
  return _wallaby.power_level()
power_level = _wallaby.power_level

def power_level_nimh():
  return _wallaby.power_level_nimh()
power_level_nimh = _wallaby.power_level_nimh

def power_level_lipo():
  return _wallaby.power_level_lipo()
power_level_lipo = _wallaby.power_level_lipo

def power_level_life():
  return _wallaby.power_level_life()
power_level_life = _wallaby.power_level_life

def analog(*args):
  return _wallaby.analog(*args)
analog = _wallaby.analog

def analog8(*args):
  return _wallaby.analog8(*args)
analog8 = _wallaby.analog8

def analog10(*args):
  return _wallaby.analog10(*args)
analog10 = _wallaby.analog10

def analog12(*args):
  return _wallaby.analog12(*args)
analog12 = _wallaby.analog12

def analog_et(*args):
  return _wallaby.analog_et(*args)
analog_et = _wallaby.analog_et

def set_analog_pullup(*args):
  return _wallaby.set_analog_pullup(*args)
set_analog_pullup = _wallaby.set_analog_pullup

def get_analog_pullup(*args):
  return _wallaby.get_analog_pullup(*args)
get_analog_pullup = _wallaby.get_analog_pullup

def set_auto_publish(*args):
  return _wallaby.set_auto_publish(*args)
set_auto_publish = _wallaby.set_auto_publish

def publish():
  return _wallaby.publish()
publish = _wallaby.publish

def halt():
  return _wallaby.halt()
halt = _wallaby.halt

def freeze_halt():
  return _wallaby.freeze_halt()
freeze_halt = _wallaby.freeze_halt

def accel_x():
  return _wallaby.accel_x()
accel_x = _wallaby.accel_x

def accel_y():
  return _wallaby.accel_y()
accel_y = _wallaby.accel_y

def accel_z():
  return _wallaby.accel_z()
accel_z = _wallaby.accel_z

def accel_calibrate():
  return _wallaby.accel_calibrate()
accel_calibrate = _wallaby.accel_calibrate

def calibrate_compass():
  return _wallaby.calibrate_compass()
calibrate_compass = _wallaby.calibrate_compass

def set_compass_params(*args):
  return _wallaby.set_compass_params(*args)
set_compass_params = _wallaby.set_compass_params

def get_compass_angle():
  return _wallaby.get_compass_angle()
get_compass_angle = _wallaby.get_compass_angle

def gyro_x():
  return _wallaby.gyro_x()
gyro_x = _wallaby.gyro_x

def gyro_y():
  return _wallaby.gyro_y()
gyro_y = _wallaby.gyro_y

def gyro_z():
  return _wallaby.gyro_z()
gyro_z = _wallaby.gyro_z

def gyro_calibrate():
  return _wallaby.gyro_calibrate()
gyro_calibrate = _wallaby.gyro_calibrate

def magneto_x():
  return _wallaby.magneto_x()
magneto_x = _wallaby.magneto_x

def magneto_y():
  return _wallaby.magneto_y()
magneto_y = _wallaby.magneto_y

def magneto_z():
  return _wallaby.magneto_z()
magneto_z = _wallaby.magneto_z

def magneto_calibrate():
  return _wallaby.magneto_calibrate()
magneto_calibrate = _wallaby.magneto_calibrate
class pixel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pixel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pixel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _wallaby.pixel_r_set
    __swig_getmethods__["r"] = _wallaby.pixel_r_get
    if _newclass:r = _swig_property(_wallaby.pixel_r_get, _wallaby.pixel_r_set)
    __swig_setmethods__["g"] = _wallaby.pixel_g_set
    __swig_getmethods__["g"] = _wallaby.pixel_g_get
    if _newclass:g = _swig_property(_wallaby.pixel_g_get, _wallaby.pixel_g_set)
    __swig_setmethods__["b"] = _wallaby.pixel_b_set
    __swig_getmethods__["b"] = _wallaby.pixel_b_get
    if _newclass:b = _swig_property(_wallaby.pixel_b_get, _wallaby.pixel_b_set)
    def __init__(self): 
        this = _wallaby.new_pixel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_pixel
    __del__ = lambda self : None;
pixel_swigregister = _wallaby.pixel_swigregister
pixel_swigregister(pixel)

LOW_RES = _wallaby.LOW_RES
MED_RES = _wallaby.MED_RES
HIGH_RES = _wallaby.HIGH_RES
NATIVE_RES = _wallaby.NATIVE_RES
WHITE_2016 = _wallaby.WHITE_2016
BLACK_2017 = _wallaby.BLACK_2017

def camera_open():
  return _wallaby.camera_open()
camera_open = _wallaby.camera_open

def camera_open_black():
  return _wallaby.camera_open_black()
camera_open_black = _wallaby.camera_open_black

def camera_open_at_res(*args):
  return _wallaby.camera_open_at_res(*args)
camera_open_at_res = _wallaby.camera_open_at_res

def camera_open_device(*args):
  return _wallaby.camera_open_device(*args)
camera_open_device = _wallaby.camera_open_device

def camera_open_device_model_at_res(*args):
  return _wallaby.camera_open_device_model_at_res(*args)
camera_open_device_model_at_res = _wallaby.camera_open_device_model_at_res

def camera_load_config(*args):
  return _wallaby.camera_load_config(*args)
camera_load_config = _wallaby.camera_load_config

def set_camera_width(*args):
  return _wallaby.set_camera_width(*args)
set_camera_width = _wallaby.set_camera_width

def set_camera_height(*args):
  return _wallaby.set_camera_height(*args)
set_camera_height = _wallaby.set_camera_height

def get_camera_width():
  return _wallaby.get_camera_width()
get_camera_width = _wallaby.get_camera_width

def get_camera_height():
  return _wallaby.get_camera_height()
get_camera_height = _wallaby.get_camera_height

def camera_update():
  return _wallaby.camera_update()
camera_update = _wallaby.camera_update

def get_camera_pixel(*args):
  return _wallaby.get_camera_pixel(*args)
get_camera_pixel = _wallaby.get_camera_pixel

def get_channel_count():
  return _wallaby.get_channel_count()
get_channel_count = _wallaby.get_channel_count

def get_object_count(*args):
  return _wallaby.get_object_count(*args)
get_object_count = _wallaby.get_object_count

def get_object_data(*args):
  return _wallaby.get_object_data(*args)
get_object_data = _wallaby.get_object_data

def get_code_num(*args):
  return _wallaby.get_code_num(*args)
get_code_num = _wallaby.get_code_num

def get_object_data_length(*args):
  return _wallaby.get_object_data_length(*args)
get_object_data_length = _wallaby.get_object_data_length

def get_object_confidence(*args):
  return _wallaby.get_object_confidence(*args)
get_object_confidence = _wallaby.get_object_confidence

def get_object_area(*args):
  return _wallaby.get_object_area(*args)
get_object_area = _wallaby.get_object_area

def get_object_bbox(*args):
  return _wallaby.get_object_bbox(*args)
get_object_bbox = _wallaby.get_object_bbox

def get_object_bbox_ulx(*args):
  return _wallaby.get_object_bbox_ulx(*args)
get_object_bbox_ulx = _wallaby.get_object_bbox_ulx

def get_object_bbox_uly(*args):
  return _wallaby.get_object_bbox_uly(*args)
get_object_bbox_uly = _wallaby.get_object_bbox_uly

def get_object_bbox_brx(*args):
  return _wallaby.get_object_bbox_brx(*args)
get_object_bbox_brx = _wallaby.get_object_bbox_brx

def get_object_bbox_bry(*args):
  return _wallaby.get_object_bbox_bry(*args)
get_object_bbox_bry = _wallaby.get_object_bbox_bry

def get_object_bbox_width(*args):
  return _wallaby.get_object_bbox_width(*args)
get_object_bbox_width = _wallaby.get_object_bbox_width

def get_object_bbox_height(*args):
  return _wallaby.get_object_bbox_height(*args)
get_object_bbox_height = _wallaby.get_object_bbox_height

def get_object_centroid(*args):
  return _wallaby.get_object_centroid(*args)
get_object_centroid = _wallaby.get_object_centroid

def get_object_centroid_column(*args):
  return _wallaby.get_object_centroid_column(*args)
get_object_centroid_column = _wallaby.get_object_centroid_column

def get_object_centroid_x(*args):
  return _wallaby.get_object_centroid_x(*args)
get_object_centroid_x = _wallaby.get_object_centroid_x

def get_object_centroid_row(*args):
  return _wallaby.get_object_centroid_row(*args)
get_object_centroid_row = _wallaby.get_object_centroid_row

def get_object_centroid_y(*args):
  return _wallaby.get_object_centroid_y(*args)
get_object_centroid_y = _wallaby.get_object_centroid_y

def get_object_center(*args):
  return _wallaby.get_object_center(*args)
get_object_center = _wallaby.get_object_center

def get_object_center_column(*args):
  return _wallaby.get_object_center_column(*args)
get_object_center_column = _wallaby.get_object_center_column

def get_object_center_x(*args):
  return _wallaby.get_object_center_x(*args)
get_object_center_x = _wallaby.get_object_center_x

def get_object_center_row(*args):
  return _wallaby.get_object_center_row(*args)
get_object_center_row = _wallaby.get_object_center_row

def get_object_center_y(*args):
  return _wallaby.get_object_center_y(*args)
get_object_center_y = _wallaby.get_object_center_y

def camera_close():
  return _wallaby.camera_close()
camera_close = _wallaby.camera_close

def set_camera_config_base_path(*args):
  return _wallaby.set_camera_config_base_path(*args)
set_camera_config_base_path = _wallaby.set_camera_config_base_path

def get_camera_frame_row(*args):
  return _wallaby.get_camera_frame_row(*args)
get_camera_frame_row = _wallaby.get_camera_frame_row

def get_camera_frame():
  return _wallaby.get_camera_frame()
get_camera_frame = _wallaby.get_camera_frame

def get_camera_element_size():
  return _wallaby.get_camera_element_size()
get_camera_element_size = _wallaby.get_camera_element_size

def set_a_button_text(*args):
  return _wallaby.set_a_button_text(*args)
set_a_button_text = _wallaby.set_a_button_text

def set_b_button_text(*args):
  return _wallaby.set_b_button_text(*args)
set_b_button_text = _wallaby.set_b_button_text

def set_c_button_text(*args):
  return _wallaby.set_c_button_text(*args)
set_c_button_text = _wallaby.set_c_button_text

def set_x_button_text(*args):
  return _wallaby.set_x_button_text(*args)
set_x_button_text = _wallaby.set_x_button_text

def set_y_button_text(*args):
  return _wallaby.set_y_button_text(*args)
set_y_button_text = _wallaby.set_y_button_text

def set_z_button_text(*args):
  return _wallaby.set_z_button_text(*args)
set_z_button_text = _wallaby.set_z_button_text

def a_button():
  return _wallaby.a_button()
a_button = _wallaby.a_button

def b_button():
  return _wallaby.b_button()
b_button = _wallaby.b_button

def c_button():
  return _wallaby.c_button()
c_button = _wallaby.c_button

def x_button():
  return _wallaby.x_button()
x_button = _wallaby.x_button

def y_button():
  return _wallaby.y_button()
y_button = _wallaby.y_button

def z_button():
  return _wallaby.z_button()
z_button = _wallaby.z_button

def side_button():
  return _wallaby.side_button()
side_button = _wallaby.side_button

def black_button():
  return _wallaby.black_button()
black_button = _wallaby.black_button

def push_button():
  return _wallaby.push_button()
push_button = _wallaby.push_button

def left_button():
  return _wallaby.left_button()
left_button = _wallaby.left_button

def right_button():
  return _wallaby.right_button()
right_button = _wallaby.right_button

def a_button_clicked():
  return _wallaby.a_button_clicked()
a_button_clicked = _wallaby.a_button_clicked

def b_button_clicked():
  return _wallaby.b_button_clicked()
b_button_clicked = _wallaby.b_button_clicked

def c_button_clicked():
  return _wallaby.c_button_clicked()
c_button_clicked = _wallaby.c_button_clicked

def x_button_clicked():
  return _wallaby.x_button_clicked()
x_button_clicked = _wallaby.x_button_clicked

def y_button_clicked():
  return _wallaby.y_button_clicked()
y_button_clicked = _wallaby.y_button_clicked

def z_button_clicked():
  return _wallaby.z_button_clicked()
z_button_clicked = _wallaby.z_button_clicked

def side_button_clicked():
  return _wallaby.side_button_clicked()
side_button_clicked = _wallaby.side_button_clicked

def any_button():
  return _wallaby.any_button()
any_button = _wallaby.any_button

def extra_buttons_show():
  return _wallaby.extra_buttons_show()
extra_buttons_show = _wallaby.extra_buttons_show

def extra_buttons_hide():
  return _wallaby.extra_buttons_hide()
extra_buttons_hide = _wallaby.extra_buttons_hide

def get_extra_buttons_visible():
  return _wallaby.get_extra_buttons_visible()
get_extra_buttons_visible = _wallaby.get_extra_buttons_visible

def set_extra_buttons_visible(*args):
  return _wallaby.set_extra_buttons_visible(*args)
set_extra_buttons_visible = _wallaby.set_extra_buttons_visible

def shut_down_in(*args):
  return _wallaby.shut_down_in(*args)
shut_down_in = _wallaby.shut_down_in

def wait_for_light(*args):
  return _wallaby.wait_for_light(*args)
wait_for_light = _wallaby.wait_for_light

def console_clear():
  return _wallaby.console_clear()
console_clear = _wallaby.console_clear

def beep():
  return _wallaby.beep()
beep = _wallaby.beep
class mutex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mutex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mutex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _wallaby.mutex_data_set
    __swig_getmethods__["data"] = _wallaby.mutex_data_get
    if _newclass:data = _swig_property(_wallaby.mutex_data_get, _wallaby.mutex_data_set)
    def __init__(self): 
        this = _wallaby.new_mutex()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_mutex
    __del__ = lambda self : None;
mutex_swigregister = _wallaby.mutex_swigregister
mutex_swigregister(mutex)

class thread(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, thread, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, thread, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _wallaby.thread_data_set
    __swig_getmethods__["data"] = _wallaby.thread_data_get
    if _newclass:data = _swig_property(_wallaby.thread_data_get, _wallaby.thread_data_set)
    def __init__(self): 
        this = _wallaby.new_thread()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wallaby.delete_thread
    __del__ = lambda self : None;
thread_swigregister = _wallaby.thread_swigregister
thread_swigregister(thread)


def mutex_create():
  return _wallaby.mutex_create()
mutex_create = _wallaby.mutex_create

def mutex_lock(*args):
  return _wallaby.mutex_lock(*args)
mutex_lock = _wallaby.mutex_lock

def mutex_trylock(*args):
  return _wallaby.mutex_trylock(*args)
mutex_trylock = _wallaby.mutex_trylock

def mutex_unlock(*args):
  return _wallaby.mutex_unlock(*args)
mutex_unlock = _wallaby.mutex_unlock

def mutex_destroy(*args):
  return _wallaby.mutex_destroy(*args)
mutex_destroy = _wallaby.mutex_destroy

def thread_create(*args):
  return _wallaby.thread_create(*args)
thread_create = _wallaby.thread_create

def thread_start(*args):
  return _wallaby.thread_start(*args)
thread_start = _wallaby.thread_start

def thread_wait(*args):
  return _wallaby.thread_wait(*args)
thread_wait = _wallaby.thread_wait

def thread_destroy(*args):
  return _wallaby.thread_destroy(*args)
thread_destroy = _wallaby.thread_destroy

def digital(*args):
  return _wallaby.digital(*args)
digital = _wallaby.digital

def set_digital_value(*args):
  return _wallaby.set_digital_value(*args)
set_digital_value = _wallaby.set_digital_value

def get_digital_value(*args):
  return _wallaby.get_digital_value(*args)
get_digital_value = _wallaby.get_digital_value

def set_digital_output(*args):
  return _wallaby.set_digital_output(*args)
set_digital_output = _wallaby.set_digital_output

def get_digital_output(*args):
  return _wallaby.get_digital_output(*args)
get_digital_output = _wallaby.get_digital_output

def get_digital_pullup(*args):
  return _wallaby.get_digital_pullup(*args)
get_digital_pullup = _wallaby.get_digital_pullup

def set_digital_pullup(*args):
  return _wallaby.set_digital_pullup(*args)
set_digital_pullup = _wallaby.set_digital_pullup
# This file is compatible with both classic and new-style classes.


