libwallaby: include/wallaby/geom.h File Reference
geom.h File Reference
#include "export.h"
#include "vtable.h"
Classes
struct point2
struct point3
struct rectangle
Typedefs
typedef struct point2 point2
typedef struct point3 point3
typedef struct rectangle rectangle
Functions
VF EXPORT_SYM point2 create_point2 (int x, int y)
VF EXPORT_SYM point3 create_point3 (int x, int y, int z)
VF EXPORT_SYM rectangle create_rectangle (int ulx, int uly, int width, int height)
Typedef Documentation
typedef struct point2 point2
typedef struct point3 point3
typedef struct rectangle rectangle
Function Documentation
VF EXPORT_SYM point2 create_point2 (int x, int y)
Referenced by Point2< unsigned >::toCPoint2().
VF EXPORT_SYM point3 create_point3 (int x, int y, int z)
Referenced by Point3< T >::toCPoint3().
VF EXPORT_SYM rectangle create_rectangle (int ulx, int uly, int width, int height)
Referenced by Rect< unsigned >::toCRectangle().