.TH "/home/zachary/libwallaby/module/motor/public/kipr/motor Directory Reference" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/motor/public/kipr/motor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmotor\&.h\fP"
.br
.ti -1c
.RI "file \fBmotor\&.hpp\fP"
.br
.in -1c
