.TH "/home/zachary/libwallaby/module/graphics/public/kipr/graphics Directory Reference" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/graphics/public/kipr/graphics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgraphics\&.h\fP"
.br
.RI "Methods for displaying graphics to the screen\&. "
.ti -1c
.RI "file \fBgraphics_characters\&.h\fP"
.br
.RI "functions for adding alphameric characters to graphics windows\&. "
.ti -1c
.RI "file \fBgraphics_key_code\&.h\fP"
.br
.RI "Key codes used in the graphics window\&. "
.in -1c
