.TH "/home/zachary/libwallaby/module/wait_for/public/kipr/wait_for Directory Reference" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/wait_for/public/kipr/wait_for Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwait_for\&.h\fP"
.br
.in -1c
