.TH "/home/zachary/libwallaby/module/gyro/public/kipr/gyro Directory Reference" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/gyro/public/kipr/gyro Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgyro\&.h\fP"
.br
.ti -1c
.RI "file \fBgyro\&.hpp\fP"
.br
.in -1c
