.TH "/home/zachary/libwallaby/module/console/public/kipr/console Directory Reference" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/console/public/kipr/console Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconsole\&.h\fP"
.br
.RI "Methods for working with the console screen\&. "
.ti -1c
.RI "file \fBconsole\&.hpp\fP"
.br
.RI "Classes for working with the console screen\&. "
.ti -1c
.RI "file \fBdisplay\&.h\fP"
.br
.in -1c
