.TH "accel" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accel \- Accelerometer
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "signed short \fBaccel_x\fP ()"
.br
.RI "Gets the sensed x acceleration\&. "
.ti -1c
.RI "signed short \fBaccel_y\fP ()"
.br
.RI "Gets the sensed y acceleration\&. "
.ti -1c
.RI "signed short \fBaccel_z\fP ()"
.br
.RI "Gets the sensed z acceleration\&. "
.ti -1c
.RI "int \fBaccel_calibrate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int accel_calibrate ()"
Initiates a calibration of the accelerometer 
.PP
\fBNote\fP
.RS 4
Not Yet Implemented 
.RE
.PP
\fBReturns\fP
.RS 4
1: success 0: failure 
.RE
.PP

.SS "signed short accel_x ()"

.PP
Gets the sensed x acceleration\&. Wallaby: +/- 2G range, 1024 per G
.PP
Wombat: +/- 2G range, 1024 per G
.PP
This should be approximately 0 when at rest and flat on a table 
.PP
\fBReturns\fP
.RS 4
The latest signed x acceleration value 
.RE
.PP

.SS "signed short accel_y ()"

.PP
Gets the sensed y acceleration\&. Wallaby: +/- 2G range, 1024 per G
.PP
Wombat: +/- 2G range, 1024 per G
.PP
This should be approximately 0 when at rest and flat on a table 
.PP
\fBReturns\fP
.RS 4
The latest signed y acceleration value 
.RE
.PP

.SS "signed short accel_z ()"

.PP
Gets the sensed z acceleration\&. Wallaby: +/- 2G range, 1024 per G
.PP
Wallaby: This should be approximately -1024 when at rest and flat on a table
.PP
Wombat: +/- 2G range, 1024 per G
.PP
Wombat: This should be approximately -512 when at rest and flat on a table 
.PP
\fBReturns\fP
.RS 4
The latest signed z acceleration value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
