.TH "/home/zachary/libwallaby/module/accel/public/kipr/accel/accel.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/accel/public/kipr/accel/accel.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/sensor/sensor\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::accel::Acceleration\fP"
.br
.ti -1c
.RI "class \fBkipr::accel::AccelX\fP"
.br
.ti -1c
.RI "class \fBkipr::accel::AccelY\fP"
.br
.ti -1c
.RI "class \fBkipr::accel::AccelZ\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::accel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
