.TH "/home/zachary/libwallaby/module/accel/public/kipr/accel/accel.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/accel/public/kipr/accel/accel.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "signed short \fBaccel_x\fP ()"
.br
.RI "Gets the sensed x acceleration\&. "
.ti -1c
.RI "signed short \fBaccel_y\fP ()"
.br
.RI "Gets the sensed y acceleration\&. "
.ti -1c
.RI "signed short \fBaccel_z\fP ()"
.br
.RI "Gets the sensed z acceleration\&. "
.ti -1c
.RI "int \fBaccel_calibrate\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
