.TH "/home/zachary/libwallaby/module/analog/public/kipr/analog/analog.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/analog/public/kipr/analog/analog.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/sensor/sensor\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::analog::Analog\fP"
.br
.ti -1c
.RI "class \fBkipr::analog::Analog8\fP"
.br
.ti -1c
.RI "class \fBkipr::analog::Analog10\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::analog\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
