.TH "/home/zachary/libwallaby/module/audio/public/kipr/audio/audio.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/audio/public/kipr/audio/audio.h
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBbeep\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEXPORT_SYM\fP void beep (void)"
Trigger an audible beep 
.PP
\fBNote\fP
.RS 4
does not seem to work on the Wallaby 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
