.TH "/home/zachary/libwallaby/module/battery/public/kipr/battery/battery.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/battery/public/kipr/battery/battery.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbattery_charging\fP ()"
.br
.ti -1c
.RI "float \fBpower_level\fP ()"
.br
.ti -1c
.RI "float \fBpower_level_nimh\fP ()"
.br
.ti -1c
.RI "float \fBpower_level_lipo\fP ()"
.br
.ti -1c
.RI "float \fBpower_level_life\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Joshua southerland 
.RE
.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
