.TH "/home/zachary/libwallaby/module/button/public/kipr/button/button_ids.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/button/public/kipr/button/button_ids.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::button\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBkipr::button::Id\fP { \fBkipr::button::A\fP = 0, \fBkipr::button::B\fP, \fBkipr::button::C\fP, \fBkipr::button::X\fP, \fBkipr::button::Y\fP, \fBkipr::button::Z\fP, \fBkipr::button::Left\fP, \fBkipr::button::Right\fP, \fBkipr::button::Physical\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
