.TH "/home/zachary/libwallaby/module/button/public/kipr/button/button.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/button/public/kipr/button/button.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/sensor/sensor\&.hpp'\fP
.br
\fC#include 'button_ids\&.hpp'\fP
.br
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::button::AbstractButton\fP"
.br
.ti -1c
.RI "class \fBkipr::button::AbstractTextButton\fP"
.br
.ti -1c
.RI "class \fBkipr::button::IdButton\fP"
.br
.ti -1c
.RI "class \fBkipr::button::ExtraButtons\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::button\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::A\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::B\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::C\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::X\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::Y\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::Z\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::Left\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton \fBkipr::button::Right\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP IdButton *const \fBkipr::button::all\fP [8]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
