.TH "/home/zachary/libwallaby/module/button/public/kipr/button/button.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/button/public/kipr/button/button.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_a_button_text\fP (const char *text)"
.br
.ti -1c
.RI "void \fBset_b_button_text\fP (const char *text)"
.br
.ti -1c
.RI "void \fBset_c_button_text\fP (const char *text)"
.br
.ti -1c
.RI "void \fBset_x_button_text\fP (const char *text)"
.br
.ti -1c
.RI "void \fBset_y_button_text\fP (const char *text)"
.br
.ti -1c
.RI "void \fBset_z_button_text\fP (const char *text)"
.br
.ti -1c
.RI "int \fBa_button\fP ()"
.br
.ti -1c
.RI "int \fBb_button\fP ()"
.br
.ti -1c
.RI "int \fBc_button\fP ()"
.br
.ti -1c
.RI "int \fBx_button\fP ()"
.br
.ti -1c
.RI "int \fBy_button\fP ()"
.br
.ti -1c
.RI "int \fBz_button\fP ()"
.br
.ti -1c
.RI "int \fBside_button\fP ()"
.br
.ti -1c
.RI "int \fBblack_button\fP ()"
.br
.ti -1c
.RI "int \fBpush_button\fP ()"
.br
.ti -1c
.RI "int \fBleft_button\fP ()"
.br
.ti -1c
.RI "int \fBright_button\fP ()"
.br
.ti -1c
.RI "int \fBa_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBb_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBc_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBx_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBy_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBz_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBside_button_clicked\fP ()"
.br
.ti -1c
.RI "int \fBany_button\fP ()"
.br
.ti -1c
.RI "void \fBextra_buttons_show\fP ()"
.br
.ti -1c
.RI "void \fBextra_buttons_hide\fP ()"
.br
.ti -1c
.RI "int \fBget_extra_buttons_visible\fP ()"
.br
.ti -1c
.RI "void \fBset_extra_buttons_visible\fP (int visible)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int push_button ()"
Gets the ousg button's state (pressed or not pressed\&.) 
.PP
\fBReturns\fP
.RS 4
1 for pressed, 0 for not pressed 
.RE
.PP
\fBSee also\fP
.RS 4
\fBa_button_clicked\fP
.RE
.PP
The ousg button is the only physical button on the Wombat 
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
