.TH "/home/zachary/libwallaby/module/camera/public/kipr/camera/camera.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/camera/public/kipr/camera/camera.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/color/color\&.hpp'\fP
.br
\fC#include 'kipr/config/config\&.hpp'\fP
.br
\fC#include 'kipr/geometry/geometry\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'kipr/camera/camera\&.h'\fP
.br
\fC#include 'kipr/camera/image\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::camera::ConfigPath\fP"
.br
.ti -1c
.RI "class \fBkipr::camera::Device\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcv\fP"
.br
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::camera\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAMERA_GROUP\fP   ('camera')"
.br
.ti -1c
.RI "#define \fBCAMERA_NUM_CHANNELS_KEY\fP   ('num_channels')"
.br
.ti -1c
.RI "#define \fBCAMERA_CHANNEL_GROUP_PREFIX\fP   ('channel_')"
.br
.ti -1c
.RI "#define \fBCAMERA_CHANNEL_TYPE_KEY\fP   ('type')"
.br
.ti -1c
.RI "#define \fBCAMERA_CHANNEL_TYPE_HSV_KEY\fP   ('hsv')"
.br
.ti -1c
.RI "#define \fBCAMERA_CHANNEL_TYPE_QR_KEY\fP   ('qr')"
.br
.ti -1c
.RI "#define \fBCAMERA_CHANNEL_TYPE_ARUCO_KEY\fP   ('aruco')"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Device * \fBkipr::camera::cDevice\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAMERA_CHANNEL_GROUP_PREFIX   ('channel_')"

.SS "#define CAMERA_CHANNEL_TYPE_ARUCO_KEY   ('aruco')"

.SS "#define CAMERA_CHANNEL_TYPE_HSV_KEY   ('hsv')"

.SS "#define CAMERA_CHANNEL_TYPE_KEY   ('type')"

.SS "#define CAMERA_CHANNEL_TYPE_QR_KEY   ('qr')"

.SS "#define CAMERA_GROUP   ('camera')"

.SS "#define CAMERA_NUM_CHANNELS_KEY   ('num_channels')"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
