.TH "/home/zachary/libwallaby/module/color/public/kipr/color/colors.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/color/public/kipr/color/colors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRED\fP   255,0,0"
.br
.ti -1c
.RI "#define \fBMAROON\fP   128,0,0"
.br
.ti -1c
.RI "#define \fBCORAL\fP   240,128,128"
.br
.ti -1c
.RI "#define \fBPINK\fP   255,105,180"
.br
.ti -1c
.RI "#define \fBROSE\fP   255,228,225"
.br
.ti -1c
.RI "#define \fBORANGE\fP   255,153,51"
.br
.ti -1c
.RI "#define \fBMAGENTA\fP   255,0,255"
.br
.ti -1c
.RI "#define \fBFUCHSIA\fP   255,0,255"
.br
.ti -1c
.RI "#define \fBPURPLE\fP   128,0,128"
.br
.ti -1c
.RI "#define \fBVIOLET\fP   138,43,226"
.br
.ti -1c
.RI "#define \fBGOLD\fP   255,215,0"
.br
.ti -1c
.RI "#define \fBYELLOW\fP   255,255,0"
.br
.ti -1c
.RI "#define \fBLIME\fP   0,255,0"
.br
.ti -1c
.RI "#define \fBGREEN\fP   0,255,0"
.br
.ti -1c
.RI "#define \fBOLIVE\fP   128,128,0"
.br
.ti -1c
.RI "#define \fBCYAN\fP   0,255,255"
.br
.ti -1c
.RI "#define \fBAQUA\fP   0,255,255"
.br
.ti -1c
.RI "#define \fBTEAL\fP   0,128,128"
.br
.ti -1c
.RI "#define \fBBLUE\fP   0,0,255"
.br
.ti -1c
.RI "#define \fBNAVY\fP   0,0,128"
.br
.ti -1c
.RI "#define \fBALMOND\fP   255,235,205"
.br
.ti -1c
.RI "#define \fBLTBROWN\fP   255,229,220"
.br
.ti -1c
.RI "#define \fBBROWN\fP   139,69,19"
.br
.ti -1c
.RI "#define \fBSIENNA\fP   160,82,45"
.br
.ti -1c
.RI "#define \fBWHITE\fP   255,255,255"
.br
.ti -1c
.RI "#define \fBBLACK\fP   0,0,0"
.br
.ti -1c
.RI "#define \fBDKGRAY\fP   84,84,84"
.br
.ti -1c
.RI "#define \fBGRAY\fP   128,128,128"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALMOND   255,235,205"

.SS "#define AQUA   0,255,255"

.SS "#define BLACK   0,0,0"

.SS "#define BLUE   0,0,255"

.SS "#define BROWN   139,69,19"

.SS "#define CORAL   240,128,128"

.SS "#define CYAN   0,255,255"

.SS "#define DKGRAY   84,84,84"

.SS "#define FUCHSIA   255,0,255"

.SS "#define GOLD   255,215,0"

.SS "#define GRAY   128,128,128"

.SS "#define GREEN   0,255,0"

.SS "#define LIME   0,255,0"

.SS "#define LTBROWN   255,229,220"

.SS "#define MAGENTA   255,0,255"

.SS "#define MAROON   128,0,0"

.SS "#define NAVY   0,0,128"

.SS "#define OLIVE   128,128,0"

.SS "#define ORANGE   255,153,51"

.SS "#define PINK   255,105,180"

.SS "#define PURPLE   128,0,128"

.SS "#define RED   255,0,0"

.SS "#define ROSE   255,228,225"

.SS "#define SIENNA   160,82,45"

.SS "#define TEAL   0,128,128"

.SS "#define VIOLET   138,43,226"

.SS "#define WHITE   255,255,255"

.SS "#define YELLOW   255,255,0"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
