.TH "/home/zachary/libwallaby/module/compass/public/kipr/compass/compass.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/compass/public/kipr/compass/compass.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcalibrate_compass\fP ()"
.br
.ti -1c
.RI "void \fBset_compass_params\fP (float meanX, float meanY, float meanZ, float W1, float W2, float div_E1, float div_E2)"
.br
.ti -1c
.RI "float \fBget_compass_angle\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
