.TH "/home/zachary/libwallaby/module/console/public/kipr/console/console.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/console/public/kipr/console/console.hpp \- Classes for working with the console screen\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::console::Console\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::console\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes for working with the console screen\&. 


.PP
\fBCopyright\fP
.RS 4
KISS Insitute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
