.TH "/home/zachary/libwallaby/module/core/public/kipr/core/core.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/core/public/kipr/core/core.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBkipr_git_branch\fP ()"
.br
.ti -1c
.RI "const char * \fBkipr_git_commit_hash\fP ()"
.br
.ti -1c
.RI "int \fBkipr_version_major\fP ()"
.br
.ti -1c
.RI "int \fBkipr_version_minor\fP ()"
.br
.ti -1c
.RI "int \fBkipr_version_patch\fP ()"
.br
.ti -1c
.RI "const char * \fBkipr_version\fP ()"
.br
.ti -1c
.RI "const char * \fBkipr_build_datetime\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* kipr_build_datetime ()"

.SS "const char* kipr_git_branch ()"

.SS "const char* kipr_git_commit_hash ()"

.SS "const char* kipr_version ()"

.SS "int kipr_version_major ()"

.SS "int kipr_version_minor ()"

.SS "int kipr_version_patch ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
