.TH "/home/zachary/libwallaby/module/create/public/kipr/create/create.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/create/public/kipr/create/create.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <termios\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'kipr/sensor/sensor\&.hpp'\fP
.br
\fC#include 'kipr/button/button\&.hpp'\fP
.br
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::create::CreateScript\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreateState\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_1\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_2\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_3\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_4\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_5\fP"
.br
.ti -1c
.RI "struct \fBkipr::create::CreatePackets::_101\fP"
.br
.ti -1c
.RI "class \fBkipr::create::Create\fP"
.br
.RI "Facilitates communication with the iRobot (R) \fBCreate\fP (TM) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::create\fP"
.br
.ti -1c
.RI " \fBkipr::create::CreatePackets\fP"
.br
.ti -1c
.RI " \fBkipr::create::sensors\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.14159f"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Braden McDorman 
.RE
.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.14159f"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
