.TH "/home/zachary/libwallaby/module/create/public/kipr/create/create_codes.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/create/public/kipr/create/create_codes.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOI_START\fP   128"
.br
.ti -1c
.RI "#define \fBOI_BAUD\fP   129"
.br
.ti -1c
.RI "#define \fBOI_SAFE\fP   131"
.br
.ti -1c
.RI "#define \fBOI_FULL\fP   132"
.br
.ti -1c
.RI "#define \fBOI_DEMO\fP   136"
.br
.ti -1c
.RI "#define \fBOI_DRIVE\fP   137"
.br
.ti -1c
.RI "#define \fBOI_DRIVE_DIRECT\fP   145"
.br
.ti -1c
.RI "#define \fBOI_LEDS\fP   139"
.br
.ti -1c
.RI "#define \fBOI_DIGITAL_OUTPUTS\fP   147"
.br
.ti -1c
.RI "#define \fBOI_LOW_SIDE_DRIVERS\fP   138"
.br
.ti -1c
.RI "#define \fBOI_SEND_IR\fP   151"
.br
.ti -1c
.RI "#define \fBOI_SONG\fP   140"
.br
.ti -1c
.RI "#define \fBOI_PLAY_SONG\fP   141"
.br
.ti -1c
.RI "#define \fBOI_SENSORS\fP   142"
.br
.ti -1c
.RI "#define \fBOI_QUERY_LIST\fP   149"
.br
.ti -1c
.RI "#define \fBOI_STREAM\fP   148"
.br
.ti -1c
.RI "#define \fBOI_PAUSE_RESUME_STREAM\fP   150"
.br
.ti -1c
.RI "#define \fBOI_SCRIPT\fP   152"
.br
.ti -1c
.RI "#define \fBOI_PLAY_SCRIPT\fP   153"
.br
.ti -1c
.RI "#define \fBOI_SHOW_SCRIPT\fP   154"
.br
.ti -1c
.RI "#define \fBOI_WAIT_TIME\fP   155"
.br
.ti -1c
.RI "#define \fBOI_WAIT_DISTANCE\fP   156"
.br
.ti -1c
.RI "#define \fBOI_WAIT_ANGLE\fP   157"
.br
.ti -1c
.RI "#define \fBOI_WAIT_EVENT\fP   156"
.br
.ti -1c
.RI "#define \fBOI_BUMPS_AND_WHEEL_DROPS\fP   7"
.br
.ti -1c
.RI "#define \fBOI_WALL\fP   8"
.br
.ti -1c
.RI "#define \fBOI_CLIFF_LEFT\fP   9"
.br
.ti -1c
.RI "#define \fBOI_CLIFF_FRONT_LEFT\fP   10"
.br
.ti -1c
.RI "#define \fBOI_CLIFF_FRONT_RIGHT\fP   11"
.br
.ti -1c
.RI "#define \fBOI_CLIFF_RIGHT\fP   12"
.br
.ti -1c
.RI "#define \fBOI_VIRTUAL_WALL\fP   13"
.br
.ti -1c
.RI "#define \fBOI_LOW_SIDE_DRIVER_AND_WHEEL_OVERCURRENTS\fP   14"
.br
.ti -1c
.RI "#define \fBOI_BUTTONS\fP   18"
.br
.ti -1c
.RI "#define \fBOI_DISTANCE\fP   19"
.br
.ti -1c
.RI "#define \fBOI_ANGLE\fP   20"
.br
.ti -1c
.RI "#define \fBOI_CHARGING_STATE\fP   21"
.br
.ti -1c
.RI "#define \fBOI_VOLTAGE\fP   22"
.br
.ti -1c
.RI "#define \fBOI_CURRENT\fP   23"
.br
.ti -1c
.RI "#define \fBOI_CARGO_BAY_DIGITAL_INPUTS\fP   32"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OI_ANGLE   20"

.SS "#define OI_BAUD   129"

.SS "#define OI_BUMPS_AND_WHEEL_DROPS   7"

.SS "#define OI_BUTTONS   18"

.SS "#define OI_CARGO_BAY_DIGITAL_INPUTS   32"

.SS "#define OI_CHARGING_STATE   21"

.SS "#define OI_CLIFF_FRONT_LEFT   10"

.SS "#define OI_CLIFF_FRONT_RIGHT   11"

.SS "#define OI_CLIFF_LEFT   9"

.SS "#define OI_CLIFF_RIGHT   12"

.SS "#define OI_CURRENT   23"

.SS "#define OI_DEMO   136"

.SS "#define OI_DIGITAL_OUTPUTS   147"

.SS "#define OI_DISTANCE   19"

.SS "#define OI_DRIVE   137"

.SS "#define OI_DRIVE_DIRECT   145"

.SS "#define OI_FULL   132"

.SS "#define OI_LEDS   139"

.SS "#define OI_LOW_SIDE_DRIVER_AND_WHEEL_OVERCURRENTS   14"

.SS "#define OI_LOW_SIDE_DRIVERS   138"

.SS "#define OI_PAUSE_RESUME_STREAM   150"

.SS "#define OI_PLAY_SCRIPT   153"

.SS "#define OI_PLAY_SONG   141"

.SS "#define OI_QUERY_LIST   149"

.SS "#define OI_SAFE   131"

.SS "#define OI_SCRIPT   152"

.SS "#define OI_SEND_IR   151"

.SS "#define OI_SENSORS   142"

.SS "#define OI_SHOW_SCRIPT   154"

.SS "#define OI_SONG   140"

.SS "#define OI_START   128"

.SS "#define OI_STREAM   148"

.SS "#define OI_VIRTUAL_WALL   13"

.SS "#define OI_VOLTAGE   22"

.SS "#define OI_WAIT_ANGLE   157"

.SS "#define OI_WAIT_DISTANCE   156"

.SS "#define OI_WAIT_EVENT   156"

.SS "#define OI_WAIT_TIME   155"

.SS "#define OI_WALL   8"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
