.TH "deprecated" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBanalog_et\fP (int port)\fP" 1c
defaulting to \fBanalog()\fP on the Wallaby  
.IP "\fBMember \fBbattery_charging\fP ()\fP" 1c
not applicable for the Wallaby controller
.PP
.IP "\fBMember \fBblack_button\fP ()\fP" 1c
Not present on the Wallaby  
.IP "\fBMember \fBget_analog_pullup\fP (int port)\fP" 1c
no effect on the Wallaby  
.IP "\fBMember \fBget_digital_pullup\fP (int port)\fP" 1c
not applicable on the Wallaby
.PP
.IP "\fBMember \fBset_a_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBset_analog_pullup\fP (int port, int pullup)\fP" 1c
no effect on the Wallaby  
.IP "\fBMember \fBset_b_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBset_c_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBset_digital_pullup\fP (int port, int pullup)\fP" 1c
not applicable on the Wallaby
.PP
.IP "\fBMember \fBset_x_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBset_y_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBset_z_button_text\fP (const char *text)\fP" 1c
not planned for the Wallaby  
.IP "\fBMember \fBside_button\fP ()\fP" 1c
Not present on the Wallaby 
.PP

