.TH "/home/zachary/libwallaby/module/digital/public/kipr/digital/digital.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/digital/public/kipr/digital/digital.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdigital\fP (int port)"
.br
.ti -1c
.RI "void \fBset_digital_value\fP (int port, int value)"
.br
.ti -1c
.RI "int \fBget_digital_value\fP (int port)"
.br
.ti -1c
.RI "void \fBset_digital_output\fP (int port, int out)"
.br
.ti -1c
.RI "int \fBget_digital_output\fP (int port)"
.br
.ti -1c
.RI "int \fBget_digital_pullup\fP (int port)"
.br
.ti -1c
.RI "void \fBset_digital_pullup\fP (int port, int pullup)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
