.TH "/home/zachary/libwallaby/module/console/public/kipr/console/display.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/console/public/kipr/console/display.h
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBdisplay_clear\fP ()"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBdisplay_printf\fP (int col, int row, const char *t,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEXPORT_SYM\fP void display_clear ()"

.SS "\fBEXPORT_SYM\fP void display_printf (int col, int row, const char * t,  \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
