.TH "/home/zachary/libwallaby/module/export/public/kipr/export/export.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/export/public/kipr/export/export.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXPORT_SYM\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EXPORT_SYM"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
