.TH "/home/zachary/libwallaby/module/geometry/public/kipr/geometry/geometry.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/geometry/public/kipr/geometry/geometry.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'geometry\&.h'\fP
.br
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::geometry::Point2< T >\fP"
.br
.ti -1c
.RI "class \fBkipr::geometry::Point3< T >\fP"
.br
.ti -1c
.RI "class \fBkipr::geometry::Rect< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::geometry\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Point2< float > \fBkipr::geometry::Point2f\fP"
.br
.ti -1c
.RI "typedef Point2< double > \fBkipr::geometry::Point2d\fP"
.br
.ti -1c
.RI "typedef Rect< float > \fBkipr::geometry::Rectf\fP"
.br
.ti -1c
.RI "typedef Rect< double > \fBkipr::geometry::Rectd\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
