.TH "/home/zachary/libwallaby/module/geometry/public/kipr/geometry/geometry.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/geometry/public/kipr/geometry/geometry.h
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpoint2\fP"
.br
.RI "A 2D point; has x and y\&. "
.ti -1c
.RI "struct \fBpoint3\fP"
.br
.RI "A 3D point; has x, y, and z\&. "
.ti -1c
.RI "struct \fBrectangle\fP"
.br
.RI "A rectangle object\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpoint2\fP \fBpoint2\fP"
.br
.RI "A 2D point; has x and y\&. "
.ti -1c
.RI "typedef struct \fBpoint3\fP \fBpoint3\fP"
.br
.RI "A 3D point; has x, y, and z\&. "
.ti -1c
.RI "typedef struct \fBrectangle\fP \fBrectangle\fP"
.br
.RI "A rectangle object\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBpoint2\fP \fBcreate_point2\fP (int x, int y)"
.br
.RI "Create a \fBpoint2\fP object\&. "
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBpoint3\fP \fBcreate_point3\fP (int x, int y, int z)"
.br
.RI "Create a \fBpoint3\fP object\&. "
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBrectangle\fP \fBcreate_rectangle\fP (int ulx, int uly, int width, int height)"
.br
.RI "Create a rectangle object\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpoint2\fP \fBpoint2\fP"

.PP
A 2D point; has x and y\&. 
.SS "typedef struct \fBpoint3\fP \fBpoint3\fP"

.PP
A 3D point; has x, y, and z\&. 
.SS "typedef struct \fBrectangle\fP \fBrectangle\fP"

.PP
A rectangle object\&. 
.SH "Function Documentation"
.PP 
.SS "\fBEXPORT_SYM\fP \fBpoint2\fP create_point2 (int x, int y)"

.PP
Create a \fBpoint2\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP - the x value of the point 
.br
\fIy\fP - the y value of the point 
.RE
.PP
\fBReturns\fP
.RS 4
\fBpoint2\fP object 
.RE
.PP

.PP
Referenced by kipr::geometry::Point2< T >::toCPoint2()\&.
.SS "\fBEXPORT_SYM\fP \fBpoint3\fP create_point3 (int x, int y, int z)"

.PP
Create a \fBpoint3\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP - the x value of the point 
.br
\fIy\fP - the y value of the point 
.br
\fIz\fP - the z value of the point 
.RE
.PP
\fBReturns\fP
.RS 4
\fBpoint3\fP object 
.RE
.PP

.PP
Referenced by kipr::geometry::Point3< T >::toCPoint3()\&.
.SS "\fBEXPORT_SYM\fP \fBrectangle\fP create_rectangle (int ulx, int uly, int width, int height)"

.PP
Create a rectangle object\&. 
.PP
\fBParameters\fP
.RS 4
\fIulx\fP - the x value of the rectangle's upper left 
.br
\fIuly\fP - the y value of the rectangle's upper left 
.br
\fIwidth\fP - the width of the rectangle 
.br
\fIheight\fP - the height of the rectangle 
.RE
.PP
\fBReturns\fP
.RS 4
rectangle object 
.RE
.PP

.PP
Referenced by kipr::geometry::Rect< T >::toCRectangle()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
