.TH "/home/zachary/libwallaby/module/gyro/public/kipr/gyro/gyro.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/gyro/public/kipr/gyro/gyro.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "signed short \fBgyro_x\fP ()"
.br
.ti -1c
.RI "signed short \fBgyro_y\fP ()"
.br
.ti -1c
.RI "signed short \fBgyro_z\fP ()"
.br
.ti -1c
.RI "int \fBgyro_calibrate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
