.TH "/home/zachary/libwallaby/module/gyro/public/kipr/gyro/gyro.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/gyro/public/kipr/gyro/gyro.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/sensor/sensor\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::gyro::Gyro\fP"
.br
.ti -1c
.RI "class \fBkipr::gyro::GyroX\fP"
.br
.ti -1c
.RI "class \fBkipr::gyro::GyroY\fP"
.br
.ti -1c
.RI "class \fBkipr::gyro::GyroZ\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::gyro\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
