.TH "Hsv" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hsv
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <color\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBh\fP"
.br
.ti -1c
.RI "unsigned char \fBs\fP"
.br
.ti -1c
.RI "unsigned char \fBv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char Hsv::h"

.SS "unsigned char Hsv::s"

.SS "unsigned char Hsv::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
