.TH "kipr::camera::ConfigPath" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::camera::ConfigPath
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <camera\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBextension\fP ()"
.br
.ti -1c
.RI "static void \fBsetBasePath\fP (const std::string &\fBpath\fP)"
.br
.ti -1c
.RI "static std::string \fBpath\fP (const std::string &name=std::string())"
.br
.ti -1c
.RI "static std::string \fBdefaultPath\fP ()"
.br
.ti -1c
.RI "static std::string \fBdefaultConfigPath\fP ()"
.br
.ti -1c
.RI "static void \fBsetDefaultConfigPath\fP (const std::string &name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::string kipr::camera::ConfigPath::defaultConfigPath ()\fC [static]\fP"

.SS "static std::string kipr::camera::ConfigPath::defaultPath ()\fC [static]\fP"

.SS "static std::string kipr::camera::ConfigPath::extension ()\fC [static]\fP"

.SS "static std::string kipr::camera::ConfigPath::path (const std::string & name = \fCstd::string()\fP)\fC [static]\fP"

.SS "static void kipr::camera::ConfigPath::setBasePath (const std::string & path)\fC [static]\fP"

.SS "static void kipr::camera::ConfigPath::setDefaultConfigPath (const std::string & name)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
