.TH "kipr::create::CreateState" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreateState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "timeval \fBtimestamp\fP"
.br
.ti -1c
.RI "int \fBdistance\fP"
.br
.ti -1c
.RI "int \fBangle\fP"
.br
.ti -1c
.RI "short \fBradius\fP"
.br
.ti -1c
.RI "short \fBrightVelocity\fP"
.br
.ti -1c
.RI "short \fBleftVelocity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Locally stored state information 
.SH "Member Data Documentation"
.PP 
.SS "int kipr::create::CreateState::angle"

.SS "int kipr::create::CreateState::distance"

.SS "short kipr::create::CreateState::leftVelocity"

.SS "short kipr::create::CreateState::radius"

.SS "short kipr::create::CreateState::rightVelocity"

.SS "timeval kipr::create::CreateState::timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
