.TH "kipr::magneto::Magneto" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::magneto::Magneto
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <magneto\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static short \fBx\fP ()"
.br
.ti -1c
.RI "static short \fBy\fP ()"
.br
.ti -1c
.RI "static short \fBz\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static short kipr::magneto::Magneto::x ()\fC [static]\fP"

.SS "static short kipr::magneto::Magneto::y ()\fC [static]\fP"

.SS "static short kipr::magneto::Magneto::z ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
