.TH "kipr::log::Log" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::log::Log
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBLog\fP > \fBPtr\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< const \fBLog\fP > \fBConstPtr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP (const std::string &module)"
.br
.ti -1c
.RI "\fBLog\fP (\fBLog\fP &&rhs)"
.br
.ti -1c
.RI "void \fBlog\fP (const \fBLevel\fP level, const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBlog\fP (const \fBLevel\fP level, const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBlog\fP (const \fBLevel\fP level)"
.br
.ti -1c
.RI "void \fBfatal\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBfatal\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBfatal\fP ()"
.br
.ti -1c
.RI "void \fBerror\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBerror\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBerror\fP ()"
.br
.ti -1c
.RI "void \fBwarning\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBwarning\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBwarning\fP ()"
.br
.ti -1c
.RI "void \fBinfo\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBinfo\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBinfo\fP ()"
.br
.ti -1c
.RI "void \fBdebug\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBdebug\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBdebug\fP ()"
.br
.ti -1c
.RI "void \fBverbose\fP (const std::string &message, const \fBLocation\fP &location)"
.br
.ti -1c
.RI "void \fBverbose\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBLogStream\fP \fBverbose\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<const \fBLog\fP> \fBkipr::log::Log::ConstPtr\fP"

.SS "typedef std::shared_ptr<\fBLog\fP> \fBkipr::log::Log::Ptr\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::log::Log::Log (const std::string & module)"

.SS "kipr::log::Log::Log (\fBLog\fP && rhs)"

.SH "Member Function Documentation"
.PP 
.SS "\fBLogStream\fP kipr::log::Log::debug ()\fC [inline]\fP"

.PP
References kipr::log::Debug, and log()\&.
.SS "void kipr::log::Log::debug (const std::string & message)\fC [inline]\fP"

.PP
References kipr::log::Debug, and log()\&.
.SS "void kipr::log::Log::debug (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References kipr::log::Debug, and log()\&.
.SS "\fBLogStream\fP kipr::log::Log::error ()\fC [inline]\fP"

.PP
References kipr::log::Error, and log()\&.
.SS "void kipr::log::Log::error (const std::string & message)\fC [inline]\fP"

.PP
References kipr::log::Error, and log()\&.
.SS "void kipr::log::Log::error (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References kipr::log::Error, and log()\&.
.SS "\fBLogStream\fP kipr::log::Log::fatal ()\fC [inline]\fP"

.PP
References kipr::log::Fatal, and log()\&.
.SS "void kipr::log::Log::fatal (const std::string & message)\fC [inline]\fP"

.PP
References kipr::log::Fatal, and log()\&.
.SS "void kipr::log::Log::fatal (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References kipr::log::Fatal, and log()\&.
.SS "\fBLogStream\fP kipr::log::Log::info ()\fC [inline]\fP"

.PP
References kipr::log::Info, and log()\&.
.SS "void kipr::log::Log::info (const std::string & message)\fC [inline]\fP"

.PP
References kipr::log::Info, and log()\&.
.SS "void kipr::log::Log::info (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References kipr::log::Info, and log()\&.
.SS "\fBLogStream\fP kipr::log::Log::log (const \fBLevel\fP level)"

.SS "void kipr::log::Log::log (const \fBLevel\fP level, const std::string & message)"

.SS "void kipr::log::Log::log (const \fBLevel\fP level, const std::string & message, const \fBLocation\fP & location)"

.PP
Referenced by debug(), error(), fatal(), info(), verbose(), and warning()\&.
.SS "\fBLogStream\fP kipr::log::Log::verbose ()\fC [inline]\fP"

.PP
References log(), and kipr::log::Verbose\&.
.SS "void kipr::log::Log::verbose (const std::string & message)\fC [inline]\fP"

.PP
References log(), and kipr::log::Verbose\&.
.SS "void kipr::log::Log::verbose (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References log(), and kipr::log::Verbose\&.
.SS "\fBLogStream\fP kipr::log::Log::warning ()\fC [inline]\fP"

.PP
References log(), and kipr::log::Warning\&.
.SS "void kipr::log::Log::warning (const std::string & message)\fC [inline]\fP"

.PP
References log(), and kipr::log::Warning\&.
.SS "void kipr::log::Log::warning (const std::string & message, const \fBLocation\fP & location)\fC [inline]\fP"

.PP
References log(), and kipr::log::Warning\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
