.TH "kipr::console::Console" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::console::Console
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <console\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Methods for working with the console inside the UI 
.SH "Member Function Documentation"
.PP 
.SS "static void kipr::console::Console::clear ()\fC [static]\fP"
Clears the console\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
