.TH "kipr::geometry::Point2< T >" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::geometry::Point2< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometry\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint2\fP (const T &\fBx\fP, const T &\fBy\fP)"
.br
.ti -1c
.RI "const T & \fBx\fP () const"
.br
.ti -1c
.RI "const T & \fBrow\fP () const"
.br
.ti -1c
.RI "const T & \fBy\fP () const"
.br
.ti -1c
.RI "const T & \fBcolumn\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (const T &\fBx\fP)"
.br
.ti -1c
.RI "void \fBsetColumn\fP (const T &\fBcolumn\fP)"
.br
.ti -1c
.RI "void \fBsetY\fP (const T &\fBy\fP)"
.br
.ti -1c
.RI "void \fBsetRow\fP (const T &\fBrow\fP)"
.br
.ti -1c
.RI "\fBpoint2\fP \fBtoCPoint2\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBkipr::geometry::Point2\fP< T >::\fBPoint2\fP (const T & x, const T & y)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const T& \fBkipr::geometry::Point2\fP< T >::column () const\fC [inline]\fP"

.SS "template<typename T > const T& \fBkipr::geometry::Point2\fP< T >::row () const\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point2\fP< T >::setColumn (const T & column)\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point2\fP< T >::setRow (const T & row)\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point2\fP< T >::setX (const T & x)\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point2\fP< T >::setY (const T & y)\fC [inline]\fP"

.SS "template<typename T > \fBpoint2\fP \fBkipr::geometry::Point2\fP< T >::toCPoint2 () const\fC [inline]\fP"

.PP
References create_point2()\&.
.SS "template<typename T > const T& \fBkipr::geometry::Point2\fP< T >::x () const\fC [inline]\fP"

.SS "template<typename T > const T& \fBkipr::geometry::Point2\fP< T >::y () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
