.TH "kipr::sensor::logic" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::sensor::logic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.ti -1c
.RI "class \fBAnd\fP"
.br
.ti -1c
.RI "class \fBOr\fP"
.br
.ti -1c
.RI "class \fBXor\fP"
.br
.ti -1c
.RI "class \fBNot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
