.TH "kipr::thread::Thread" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::thread::Thread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThread\fP ()"
.br
.ti -1c
.RI "virtual \fB~Thread\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP ()"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::thread::Thread::Thread ()"

.SS "virtual kipr::thread::Thread::~Thread ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void kipr::thread::Thread::join ()"

.SS "virtual void kipr::thread::Thread::run ()\fC [pure virtual]\fP"

.SS "void kipr::thread::Thread::start ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
