.TH "kipr::create::CreatePackets::_2" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreatePackets::_2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBir\fP"
.br
.ti -1c
.RI "unsigned char \fBbuttons\fP"
.br
.ti -1c
.RI "unsigned char \fBdistance\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBangle\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCreate\fP OI Packet 2 
.SH "Member Data Documentation"
.PP 
.SS "unsigned char kipr::create::CreatePackets::_2::angle[2]"

.SS "unsigned char kipr::create::CreatePackets::_2::buttons"

.SS "unsigned char kipr::create::CreatePackets::_2::distance[2]"

.SS "unsigned char kipr::create::CreatePackets::_2::ir"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
