.TH "kipr::gyro::Gyro" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::gyro::Gyro
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gyro\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static short \fBx\fP ()"
.br
.ti -1c
.RI "static short \fBy\fP ()"
.br
.ti -1c
.RI "static short \fBz\fP ()"
.br
.ti -1c
.RI "static bool \fBcalibrate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool kipr::gyro::Gyro::calibrate ()\fC [static]\fP"

.SS "static short kipr::gyro::Gyro::x ()\fC [static]\fP"

.SS "static short kipr::gyro::Gyro::y ()\fC [static]\fP"

.SS "static short kipr::gyro::Gyro::z ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
