.TH "kipr::button::AbstractButton" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::button::AbstractButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <button\&.hpp>\fP
.PP
Inherits \fBkipr::sensor::Sensor< bool >\fP\&.
.PP
Inherited by \fBkipr::button::AbstractTextButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AbstractButton\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetPressed\fP (bool pressed)=0"
.br
.ti -1c
.RI "bool \fBisPressed\fP () const"
.br
.ti -1c
.RI "bool \fBisNotPressed\fP () const"
.br
.ti -1c
.RI "bool \fBisClicked\fP () const"
.br
.ti -1c
.RI "virtual void \fBwaitUntilReleased\fP () const"
.br
.ti -1c
.RI "virtual void \fBwaitUntilPressed\fP () const"
.br
.ti -1c
.RI "virtual void \fBwaitUntilClicked\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual kipr::button::AbstractButton::~AbstractButton ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool kipr::button::AbstractButton::isClicked () const\fC [inline]\fP"

.SS "bool kipr::button::AbstractButton::isNotPressed () const\fC [inline]\fP"

.SS "bool kipr::button::AbstractButton::isPressed () const\fC [inline]\fP"

.SS "virtual void kipr::button::AbstractButton::setPressed (bool pressed)\fC [pure virtual]\fP"

.PP
Implemented in \fBkipr::button::IdButton\fP\&.
.SS "virtual void kipr::button::AbstractButton::waitUntilClicked () const\fC [virtual]\fP"

.SS "virtual void kipr::button::AbstractButton::waitUntilPressed () const\fC [virtual]\fP"

.SS "virtual void kipr::button::AbstractButton::waitUntilReleased () const\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
