.TH "kipr::magneto" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::magneto
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMagneto\fP"
.br
.ti -1c
.RI "class \fBMagnetoX\fP"
.br
.ti -1c
.RI "class \fBMagnetoY\fP"
.br
.ti -1c
.RI "class \fBMagnetoZ\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
