.TH "kipr::create::CreatePackets::_1" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreatePackets::_1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbumpsAndWheelDrops\fP"
.br
.ti -1c
.RI "unsigned char \fBwall\fP"
.br
.ti -1c
.RI "unsigned char \fBcliffLeft\fP"
.br
.ti -1c
.RI "unsigned char \fBcliffFrontLeft\fP"
.br
.ti -1c
.RI "unsigned char \fBcliffFrontRight\fP"
.br
.ti -1c
.RI "unsigned char \fBcliffRight\fP"
.br
.ti -1c
.RI "unsigned char \fBvirtualWall\fP"
.br
.ti -1c
.RI "unsigned char \fBcargoBayDigitalInputs\fP"
.br
.ti -1c
.RI "unsigned char \fBlowSideDriverAndWheelOvercurrents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCreate\fP OI Packet 1 
.SH "Member Data Documentation"
.PP 
.SS "unsigned char kipr::create::CreatePackets::_1::bumpsAndWheelDrops"

.SS "unsigned char kipr::create::CreatePackets::_1::cargoBayDigitalInputs"

.SS "unsigned char kipr::create::CreatePackets::_1::cliffFrontLeft"

.SS "unsigned char kipr::create::CreatePackets::_1::cliffFrontRight"

.SS "unsigned char kipr::create::CreatePackets::_1::cliffLeft"

.SS "unsigned char kipr::create::CreatePackets::_1::cliffRight"

.SS "unsigned char kipr::create::CreatePackets::_1::lowSideDriverAndWheelOvercurrents"

.SS "unsigned char kipr::create::CreatePackets::_1::virtualWall"

.SS "unsigned char kipr::create::CreatePackets::_1::wall"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
