.TH "kipr::camera" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::camera
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigPath\fP"
.br
.ti -1c
.RI "class \fBDevice\fP"
.br
.ti -1c
.RI "class \fBImage\fP"
.br
.ti -1c
.RI "class \fBObject\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBObject\fP > \fBObjectVector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDevice\fP * \fBcDevice\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBObject\fP> \fBkipr::camera::ObjectVector\fP"

.SH "Function Documentation"
.PP 
.SS "\fBDevice\fP* kipr::camera::cDevice ()"
Retrieve the device singleton that backs the libkovan C camera API 
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
