.TH "kipr::motor::BackEMF" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::motor::BackEMF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motor\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackEMF\fP (int \fBport\fP)"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.ti -1c
.RI "int \fBport\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::motor::BackEMF::BackEMF (int port)"

.SH "Member Function Documentation"
.PP 
.SS "int kipr::motor::BackEMF::port () const"

.SS "int kipr::motor::BackEMF::value () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
