.TH "kipr::battery::Battery" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::battery::Battery
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <battery\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisCharging\fP ()"
.br
.ti -1c
.RI "static float \fBpowerLevel\fP (unsigned int battery_type=0)"
.br
.ti -1c
.RI "static unsigned short \fBrawPowerADC\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool kipr::battery::Battery::isCharging ()\fC [static]\fP"

.SS "static float kipr::battery::Battery::powerLevel (unsigned int battery_type = \fC0\fP)\fC [static]\fP"

.SS "static unsigned short kipr::battery::Battery::rawPowerADC ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
