.TH "kipr::create" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCreatePackets\fP"
.br
.ti -1c
.RI " \fBsensors\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreateScript\fP"
.br
.ti -1c
.RI "struct \fBCreateState\fP"
.br
.ti -1c
.RI "class \fBCreate\fP"
.br
.RI "Facilitates communication with the iRobot (R) \fBCreate\fP (TM) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
