.TH "kipr::sensor::logic::And" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::sensor::logic::And
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logic\&.hpp>\fP
.PP
Inherits \fBkipr::sensor::logic::Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnd\fP (const \fBSensor\fP< bool > *\fBa\fP, const \fBSensor\fP< bool > *\fBb\fP, bool \fBowns\fP=false)"
.br
.ti -1c
.RI "virtual bool \fBvalue\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::sensor::logic::And::And (const \fBSensor\fP< bool > * a, const \fBSensor\fP< bool > * b, bool owns = \fCfalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool kipr::sensor::logic::And::value () const\fC [virtual]\fP"

.PP
Implements \fBkipr::sensor::Sensor< bool >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
