.TH "kipr" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBaccel\fP"
.br
.ti -1c
.RI " \fBanalog\fP"
.br
.ti -1c
.RI " \fBbattery\fP"
.br
.ti -1c
.RI " \fBbutton\fP"
.br
.ti -1c
.RI " \fBcamera\fP"
.br
.ti -1c
.RI " \fBcompass\fP"
.br
.ti -1c
.RI " \fBconfig\fP"
.br
.ti -1c
.RI " \fBconsole\fP"
.br
.ti -1c
.RI " \fBcreate\fP"
.br
.ti -1c
.RI " \fBdigital\fP"
.br
.ti -1c
.RI " \fBgeometry\fP"
.br
.ti -1c
.RI " \fBgyro\fP"
.br
.ti -1c
.RI " \fBlog\fP"
.br
.ti -1c
.RI " \fBmagneto\fP"
.br
.ti -1c
.RI " \fBmotor\fP"
.br
.ti -1c
.RI " \fBsensor\fP"
.br
.ti -1c
.RI " \fBservo\fP"
.br
.ti -1c
.RI " \fBthread\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
