.TH "kipr::geometry" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::geometry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint2\fP"
.br
.ti -1c
.RI "class \fBPoint3\fP"
.br
.ti -1c
.RI "class \fBRect\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBPoint2\fP< float > \fBPoint2f\fP"
.br
.ti -1c
.RI "typedef \fBPoint2\fP< double > \fBPoint2d\fP"
.br
.ti -1c
.RI "typedef \fBRect\fP< float > \fBRectf\fP"
.br
.ti -1c
.RI "typedef \fBRect\fP< double > \fBRectd\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBPoint2\fP<double> \fBkipr::geometry::Point2d\fP"

.SS "typedef \fBPoint2\fP<float> \fBkipr::geometry::Point2f\fP"

.SS "typedef \fBRect\fP<double> \fBkipr::geometry::Rectd\fP"

.SS "typedef \fBRect\fP<float> \fBkipr::geometry::Rectf\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
