.TH "kipr::analog::Analog10" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::analog::Analog10
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analog\&.hpp>\fP
.PP
Inherits \fBkipr::analog::Analog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnalog10\fP (unsigned char \fBport\fP)"
.br
.ti -1c
.RI "virtual \fB~Analog10\fP ()"
.br
.ti -1c
.RI "virtual unsigned short \fBvalue\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::analog::Analog10::Analog10 (unsigned char port)"

.SS "virtual kipr::analog::Analog10::~Analog10 ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual unsigned short kipr::analog::Analog10::value () const\fC [virtual]\fP"

.PP
Reimplemented from \fBkipr::analog::Analog\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
