.TH "kipr::compass::Compass" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::compass::Compass
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compass\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompass\fP ()"
.br
.ti -1c
.RI "\fB~Compass\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcalibrate\fP ()"
.br
.ti -1c
.RI "static void \fBsetParams\fP (float meanX, float meanY, float meanZ, float W1, float W2, float div_E1, float div_E2)"
.br
.ti -1c
.RI "static float \fBgetAngle\fP (void)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::compass::Compass::Compass ()"

.SS "kipr::compass::Compass::~Compass ()"

.SH "Member Function Documentation"
.PP 
.SS "static void kipr::compass::Compass::calibrate ()\fC [static]\fP"

.SS "static float kipr::compass::Compass::getAngle (void)\fC [static]\fP"

.SS "static void kipr::compass::Compass::setParams (float meanX, float meanY, float meanZ, float W1, float W2, float div_E1, float div_E2)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
