.TH "kipr::camera::Device" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::camera::Device
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <camera\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDevice\fP ()"
.br
.ti -1c
.RI "\fB~Device\fP ()"
.br
.ti -1c
.RI "bool \fBopen\fP (const int number=0, \fBResolution\fP resolution=\fBLOW_RES\fP, \fBModel\fP model=\fBWHITE_2016\fP)"
.br
.ti -1c
.RI "bool \fBisOpen\fP () const"
.br
.ti -1c
.RI "bool \fBclose\fP ()"
.br
.ti -1c
.RI "bool \fBupdate\fP ()"
.br
.ti -1c
.RI "unsigned \fBwidth\fP () const"
.br
.ti -1c
.RI "unsigned \fBheight\fP () const"
.br
.ti -1c
.RI "const std::vector< Channel * > & \fBchannels\fP () const"
.br
.ti -1c
.RI "\fBImage\fP \fBrawImage\fP () const"
.br
.ti -1c
.RI "void \fBsetConfig\fP (const \fBconfig::Config\fP &\fBconfig\fP)"
.br
.ti -1c
.RI "const \fBconfig::Config\fP & \fBconfig\fP () const"
.br
.ti -1c
.RI "const unsigned char * \fBbgr\fP () const"
.br
.ti -1c
.RI "\fBModel\fP \fBgetModel\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBresolutionToHeight\fP (\fBResolution\fP res)"
.br
.ti -1c
.RI "static unsigned int \fBresolutionToWidth\fP (\fBResolution\fP res)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::camera::Device::Device ()"

.SS "kipr::camera::Device::~Device ()"

.SH "Member Function Documentation"
.PP 
.SS "const unsigned char* kipr::camera::Device::bgr () const"

.SS "const std::vector<Channel *>& kipr::camera::Device::channels () const"

.SS "bool kipr::camera::Device::close ()"

.SS "const \fBconfig::Config\fP& kipr::camera::Device::config () const"

.SS "\fBModel\fP kipr::camera::Device::getModel ()"

.SS "unsigned kipr::camera::Device::height () const"

.SS "bool kipr::camera::Device::isOpen () const"

.SS "bool kipr::camera::Device::open (const int number = \fC0\fP, \fBResolution\fP resolution = \fC\fBLOW_RES\fP\fP, \fBModel\fP model = \fC\fBWHITE_2016\fP\fP)"

.SS "\fBImage\fP kipr::camera::Device::rawImage () const"

.SS "static unsigned int kipr::camera::Device::resolutionToHeight (\fBResolution\fP res)\fC [static]\fP"

.SS "static unsigned int kipr::camera::Device::resolutionToWidth (\fBResolution\fP res)\fC [static]\fP"

.SS "void kipr::camera::Device::setConfig (const \fBconfig::Config\fP & config)"

.SS "bool kipr::camera::Device::update ()"

.SS "unsigned kipr::camera::Device::width () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
