.TH "kipr::button::ExtraButtons" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::button::ExtraButtons
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <button\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBshow\fP ()"
.br
.ti -1c
.RI "static void \fBhide\fP ()"
.br
.ti -1c
.RI "static void \fBsetShown\fP (bool shown)"
.br
.ti -1c
.RI "static bool \fBisShown\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void kipr::button::ExtraButtons::hide ()\fC [static]\fP"

.SS "static bool kipr::button::ExtraButtons::isShown ()\fC [static]\fP"

.SS "static void kipr::button::ExtraButtons::setShown (bool shown)\fC [static]\fP"

.SS "static void kipr::button::ExtraButtons::show ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
