.TH "kipr::accel::AccelY" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::accel::AccelY
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <accel\&.hpp>\fP
.PP
Inherits \fBkipr::sensor::Sensor< short >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual short \fBvalue\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual short kipr::accel::AccelY::value () const\fC [virtual]\fP"

.PP
Implements \fBkipr::sensor::Sensor< short >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
