.TH "kipr::create::CreatePackets::_101" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreatePackets::_101
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBleftEncoderCounts\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBrightEncoderCounts\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpBits\fP"
.br
.ti -1c
.RI "unsigned char \fBlightBumpLeftSignal\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpFrontLeftSignal\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpCenterLeftSignal\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpCenterRightSignal\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpFrontRightSignal\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBlightBumpRightSignal\fP [2]"
.br
.ti -1c
.RI "char \fBleftMotorCurrent\fP [2]"
.br
.ti -1c
.RI "char \fBrightMotorCurrent\fP [2]"
.br
.ti -1c
.RI "char \fBmainBrushMotorCurrent\fP [2]"
.br
.ti -1c
.RI "char \fBsideBrushMotorCurrent\fP [2]"
.br
.ti -1c
.RI "char \fBstasis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCreate\fP OI Packet 101 
.SH "Member Data Documentation"
.PP 
.SS "unsigned char kipr::create::CreatePackets::_101::leftEncoderCounts[2]"

.SS "char kipr::create::CreatePackets::_101::leftMotorCurrent[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpBits"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpCenterLeftSignal[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpCenterRightSignal[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpFrontLeftSignal[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpFrontRightSignal[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpLeftSignal[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::lightBumpRightSignal[2]"

.SS "char kipr::create::CreatePackets::_101::mainBrushMotorCurrent[2]"

.SS "unsigned char kipr::create::CreatePackets::_101::rightEncoderCounts[2]"

.SS "char kipr::create::CreatePackets::_101::rightMotorCurrent[2]"

.SS "char kipr::create::CreatePackets::_101::sideBrushMotorCurrent[2]"

.SS "char kipr::create::CreatePackets::_101::stasis"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
