.TH "kipr::geometry::Point3< T >" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::geometry::Point3< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometry\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint3\fP (const T &\fBx\fP, const T &\fBy\fP, const T &\fBz\fP)"
.br
.ti -1c
.RI "const T & \fBx\fP () const"
.br
.ti -1c
.RI "const T & \fBy\fP () const"
.br
.ti -1c
.RI "const T & \fBz\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (const T &\fBx\fP)"
.br
.ti -1c
.RI "void \fBsetY\fP (const T &\fBy\fP)"
.br
.ti -1c
.RI "void \fBsetZ\fP (const T &\fBz\fP)"
.br
.ti -1c
.RI "\fBpoint3\fP \fBtoCPoint3\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBkipr::geometry::Point3\fP< T >::\fBPoint3\fP (const T & x, const T & y, const T & z)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBkipr::geometry::Point3\fP< T >::setX (const T & x)\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point3\fP< T >::setY (const T & y)\fC [inline]\fP"

.SS "template<typename T > void \fBkipr::geometry::Point3\fP< T >::setZ (const T & z)\fC [inline]\fP"

.SS "template<typename T > \fBpoint3\fP \fBkipr::geometry::Point3\fP< T >::toCPoint3 () const\fC [inline]\fP"

.PP
References create_point3()\&.
.SS "template<typename T > const T& \fBkipr::geometry::Point3\fP< T >::x () const\fC [inline]\fP"

.SS "template<typename T > const T& \fBkipr::geometry::Point3\fP< T >::y () const\fC [inline]\fP"

.SS "template<typename T > const T& \fBkipr::geometry::Point3\fP< T >::z () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
