.TH "kipr::motor" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::motor
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMotor\fP"
.br
.ti -1c
.RI "class \fBBackEMF\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr const std::uint8_t \fBMOTOR_COUNT\fP = 4"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr const std::uint8_t kipr::motor::MOTOR_COUNT = 4\fC [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
