.TH "kipr::config::Config" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::config::Config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <config\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfig\fP ()"
.br
.ti -1c
.RI "\fBConfig\fP (const std::map< std::string, std::string > &config)"
.br
.ti -1c
.RI "bool \fBsave\fP (const std::string &path) const"
.br
.ti -1c
.RI "void \fBbeginGroup\fP (const std::string &group)"
.br
.ti -1c
.RI "void \fBendGroup\fP ()"
.br
.ti -1c
.RI "void \fBclearGroup\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBcontainsKey\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBboolValue\fP (const std::string &key) const"
.br
.ti -1c
.RI "int \fBintValue\fP (const std::string &key) const"
.br
.ti -1c
.RI "double \fBdoubleValue\fP (const std::string &key) const"
.br
.ti -1c
.RI "std::string \fBstringValue\fP (const std::string &key) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (const std::string &key, const bool &value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const std::string &key, const int &value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const std::string &key, const double &value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const std::string &key, const char *value)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const std::string &key, const std::string &value)"
.br
.ti -1c
.RI "\fBConfig\fP \fBvalues\fP () const"
.br
.ti -1c
.RI "void \fBaddValues\fP (const \fBConfig\fP &config)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBConfig\fP * \fBload\fP (const std::string &path)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::config::Config::Config ()"

.SS "kipr::config::Config::Config (const std::map< std::string, std::string > & config)"

.SH "Member Function Documentation"
.PP 
.SS "void kipr::config::Config::addValues (const \fBConfig\fP & config)"

.SS "void kipr::config::Config::beginGroup (const std::string & group)"

.SS "bool kipr::config::Config::boolValue (const std::string & key) const"

.SS "void kipr::config::Config::clear ()"

.SS "void kipr::config::Config::clearGroup ()"

.SS "bool kipr::config::Config::containsKey (const std::string & key) const"

.SS "double kipr::config::Config::doubleValue (const std::string & key) const"

.SS "void kipr::config::Config::endGroup ()"

.SS "int kipr::config::Config::intValue (const std::string & key) const"

.SS "static \fBConfig\fP* kipr::config::Config::load (const std::string & path)\fC [static]\fP"

.SS "bool kipr::config::Config::save (const std::string & path) const"

.SS "void kipr::config::Config::setValue (const std::string & key, const bool & value)"

.SS "void kipr::config::Config::setValue (const std::string & key, const char * value)"

.SS "void kipr::config::Config::setValue (const std::string & key, const double & value)"

.SS "void kipr::config::Config::setValue (const std::string & key, const int & value)"

.SS "void kipr::config::Config::setValue (const std::string & key, const std::string & value)"

.SS "std::string kipr::config::Config::stringValue (const std::string & key) const"

.SS "\fBConfig\fP kipr::config::Config::values () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
