.TH "kipr::digital::Digital" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::digital::Digital
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <digital\&.hpp>\fP
.PP
Inherits \fBkipr::sensor::Sensor< bool >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDigital\fP (unsigned char port)"
.br
.ti -1c
.RI "void \fBsetValue\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "void \fBsetOutput\fP (bool output)"
.br
.ti -1c
.RI "bool \fBisOutput\fP () const"
.br
.ti -1c
.RI "void \fBsetPullup\fP (bool \fBpullup\fP)"
.br
.ti -1c
.RI "bool \fBpullup\fP () const"
.br
.ti -1c
.RI "virtual bool \fBvalue\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::digital::Digital::Digital (unsigned char port)"

.SH "Member Function Documentation"
.PP 
.SS "bool kipr::digital::Digital::isOutput () const"

.SS "bool kipr::digital::Digital::pullup () const"

.SS "void kipr::digital::Digital::setOutput (bool output)"

.SS "void kipr::digital::Digital::setPullup (bool pullup)"

.SS "void kipr::digital::Digital::setValue (bool value)"

.SS "virtual bool kipr::digital::Digital::value () const\fC [virtual]\fP"

.PP
Implements \fBkipr::sensor::Sensor< bool >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
