.TH "kipr::log" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::log
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFlush\fP"
.br
.ti -1c
.RI "struct \fBLocation\fP"
.br
.ti -1c
.RI "class \fBLogStream\fP"
.br
.ti -1c
.RI "class \fBLog\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBLevel\fP : char { \fBFatal\fP = '!', \fBError\fP = 'E', \fBWarning\fP = 'W', \fBInfo\fP = 'I', \fBDebug\fP = 'D', \fBVerbose\fP = 'V' }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBFlush\fP \fBflush\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBkipr::log::Level\fP : char\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFatal \fP\fP
.TP
\fB\fIError \fP\fP
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIDebug \fP\fP
.TP
\fB\fIVerbose \fP\fP
.SH "Variable Documentation"
.PP 
.SS "const \fBFlush\fP kipr::log::flush\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
