.TH "kipr::button" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::button
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractButton\fP"
.br
.ti -1c
.RI "class \fBAbstractTextButton\fP"
.br
.ti -1c
.RI "class \fBIdButton\fP"
.br
.ti -1c
.RI "class \fBExtraButtons\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBId\fP { \fBA\fP = 0, \fBB\fP, \fBC\fP, \fBX\fP, \fBY\fP, \fBZ\fP, \fBLeft\fP, \fBRight\fP, \fBPhysical\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBA\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBB\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBC\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBX\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBY\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBZ\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBLeft\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP \fBRight\fP"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBIdButton\fP *const \fBall\fP [8]"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBkipr::button::Id\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIA \fP\fP
.TP
\fB\fIB \fP\fP
.TP
\fB\fIC \fP\fP
.TP
\fB\fIX \fP\fP
.TP
\fB\fIY \fP\fP
.TP
\fB\fIZ \fP\fP
.TP
\fB\fILeft \fP\fP
.TP
\fB\fIRight \fP\fP
.TP
\fB\fIPhysical \fP\fP
.SH "Variable Documentation"
.PP 
.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::A\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP* const kipr::button::all[8]\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::B\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::C\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::Left\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::Right\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::X\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::Y\fC [extern]\fP"

.SS "\fBEXPORT_SYM\fP \fBIdButton\fP kipr::button::Z\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
