.TH "kipr::create::CreatePackets::_3" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreatePackets::_3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <create\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBchargingState\fP"
.br
.ti -1c
.RI "unsigned char \fBvoltage\fP [2]"
.br
.ti -1c
.RI "char \fBcurrent\fP [2]"
.br
.ti -1c
.RI "char \fBbatteryTemperature\fP"
.br
.ti -1c
.RI "unsigned char \fBbatteryCharge\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBbatteryCapacity\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCreate\fP OI Packet 3 
.SH "Member Data Documentation"
.PP 
.SS "unsigned char kipr::create::CreatePackets::_3::batteryCapacity[2]"

.SS "unsigned char kipr::create::CreatePackets::_3::batteryCharge[2]"

.SS "char kipr::create::CreatePackets::_3::batteryTemperature"

.SS "unsigned char kipr::create::CreatePackets::_3::chargingState"

.SS "char kipr::create::CreatePackets::_3::current[2]"

.SS "unsigned char kipr::create::CreatePackets::_3::voltage[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
