.TH "kipr::motor::Motor" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::motor::Motor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motor\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotor\fP (int \fBport\fP)"
.br
.ti -1c
.RI "void \fBclearPositionCounter\fP ()"
.br
.ti -1c
.RI "void \fBmoveAtVelocity\fP (short velocity)"
.br
.ti -1c
.RI "void \fBmoveToPosition\fP (short speed, int goalPos)"
.br
.ti -1c
.RI "void \fBmoveRelativePosition\fP (short speed, int deltaPos)"
.br
.ti -1c
.RI "void \fBsetPidGains\fP (short p, short i, short d, short pd, short id, short dd)"
.br
.ti -1c
.RI "void \fBpidGains\fP (short &p, short &i, short &d, short &pd, short &id, short &dd)"
.br
.ti -1c
.RI "void \fBfreeze\fP ()"
.br
.ti -1c
.RI "bool \fBisMotorDone\fP () const"
.br
.ti -1c
.RI "void \fBblockMotorDone\fP () const"
.br
.ti -1c
.RI "void \fBforward\fP ()"
.br
.ti -1c
.RI "void \fBbackward\fP ()"
.br
.ti -1c
.RI "void \fBmotor\fP (int percent)"
.br
.ti -1c
.RI "void \fBbaasbennaguui\fP (int percent)"
.br
.ti -1c
.RI "void \fBmotorPower\fP (int percent)"
.br
.ti -1c
.RI "void \fBoff\fP ()"
.br
.ti -1c
.RI "int \fBport\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::motor::Motor::Motor (int port)"

.SH "Member Function Documentation"
.PP 
.SS "void kipr::motor::Motor::baasbennaguui (int percent)"

.SS "void kipr::motor::Motor::backward ()"

.SS "void kipr::motor::Motor::blockMotorDone () const"

.SS "void kipr::motor::Motor::clearPositionCounter ()"

.SS "void kipr::motor::Motor::forward ()"

.SS "void kipr::motor::Motor::freeze ()"

.SS "bool kipr::motor::Motor::isMotorDone () const"

.SS "void kipr::motor::Motor::motor (int percent)"

.SS "void kipr::motor::Motor::motorPower (int percent)"

.SS "void kipr::motor::Motor::moveAtVelocity (short velocity)"

.SS "void kipr::motor::Motor::moveRelativePosition (short speed, int deltaPos)"

.SS "void kipr::motor::Motor::moveToPosition (short speed, int goalPos)"

.SS "void kipr::motor::Motor::off ()"

.SS "void kipr::motor::Motor::pidGains (short & p, short & i, short & d, short & pd, short & id, short & dd)"

.SS "int kipr::motor::Motor::port () const"

.SS "void kipr::motor::Motor::setPidGains (short p, short i, short d, short pd, short id, short dd)"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
