.TH "kipr::create::CreatePackets" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::create::CreatePackets
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_1\fP"
.br
.ti -1c
.RI "struct \fB_2\fP"
.br
.ti -1c
.RI "struct \fB_3\fP"
.br
.ti -1c
.RI "struct \fB_4\fP"
.br
.ti -1c
.RI "struct \fB_5\fP"
.br
.ti -1c
.RI "struct \fB_101\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
See the create open interface documentation for more information about these structures 
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
