.TH "kipr::servo::Servo" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::servo::Servo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <servo\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBticks_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServo\fP (int port)"
.br
.ti -1c
.RI "void \fBsetPosition\fP (\fBticks_t\fP \fBposition\fP)"
.br
.ti -1c
.RI "\fBticks_t\fP \fBposition\fP () const"
.br
.ti -1c
.RI "void \fBdisable\fP ()"
.br
.ti -1c
.RI "void \fBenable\fP ()"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool enabled)"
.br
.ti -1c
.RI "bool \fBisEnabled\fP () const"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBkipr::servo::Servo::ticks_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "kipr::servo::Servo::Servo (int port)"

.SH "Member Function Documentation"
.PP 
.SS "void kipr::servo::Servo::disable ()"

.SS "void kipr::servo::Servo::enable ()"

.SS "bool kipr::servo::Servo::isEnabled () const"

.SS "\fBticks_t\fP kipr::servo::Servo::position () const"

.SS "void kipr::servo::Servo::setEnabled (bool enabled)"

.SS "void kipr::servo::Servo::setPosition (\fBticks_t\fP position)"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
