.TH "kipr::gyro" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kipr::gyro
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGyro\fP"
.br
.ti -1c
.RI "class \fBGyroX\fP"
.br
.ti -1c
.RI "class \fBGyroY\fP"
.br
.ti -1c
.RI "class \fBGyroZ\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
