.TH "/home/zachary/libwallaby/module/log/public/kipr/log/log.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/log/public/kipr/log/log.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBkipr::log::Flush\fP"
.br
.ti -1c
.RI "struct \fBkipr::log::Location\fP"
.br
.ti -1c
.RI "class \fBkipr::log::LogStream\fP"
.br
.ti -1c
.RI "class \fBkipr::log::Log\fP"
.br
.ti -1c
.RI "struct \fBstd::hash< kipr::log::Level >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::log\fP"
.br
.ti -1c
.RI " \fBstd\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBkipr::log::Level\fP : char { \fBkipr::log::Fatal\fP = '!', \fBkipr::log::Error\fP = 'E', \fBkipr::log::Warning\fP = 'W', \fBkipr::log::Info\fP = 'I', \fBkipr::log::Debug\fP = 'D', \fBkipr::log::Verbose\fP = 'V' }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const Flush \fBkipr::log::flush\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
