.TH "/home/zachary/libwallaby/module/sensor/public/kipr/sensor/logic.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/sensor/public/kipr/sensor/logic.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'sensor\&.hpp'\fP
.br
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::sensor::logic::Base\fP"
.br
.ti -1c
.RI "class \fBkipr::sensor::logic::And\fP"
.br
.ti -1c
.RI "class \fBkipr::sensor::logic::Or\fP"
.br
.ti -1c
.RI "class \fBkipr::sensor::logic::Xor\fP"
.br
.ti -1c
.RI "class \fBkipr::sensor::logic::Not\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::sensor\fP"
.br
.ti -1c
.RI " \fBkipr::sensor::logic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
