.TH "magneto" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
magneto \- Magnetometer
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "signed short \fBmagneto_x\fP ()"
.br
.ti -1c
.RI "signed short \fBmagneto_y\fP ()"
.br
.ti -1c
.RI "signed short \fBmagneto_z\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "signed short magneto_x ()"
Gets the sensed x magneto value 
.PP
\fBReturns\fP
.RS 4
The latest signed x magneto value 
.RE
.PP

.SS "signed short magneto_y ()"
Gets the sensed x magneto value 
.PP
\fBReturns\fP
.RS 4
The latest signed y magneto value 
.RE
.PP

.SS "signed short magneto_z ()"
Gets the sensed x magneto value 
.PP
\fBReturns\fP
.RS 4
The latest signed z magneto value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
