.TH "/home/zachary/libwallaby/module/magneto/public/kipr/magneto/magneto.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/magneto/public/kipr/magneto/magneto.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "signed short \fBmagneto_x\fP ()"
.br
.ti -1c
.RI "signed short \fBmagneto_y\fP ()"
.br
.ti -1c
.RI "signed short \fBmagneto_z\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
