.TH "/home/zachary/libwallaby/module/camera/public/kipr/camera/object.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/camera/public/kipr/camera/object.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/geometry/geometry\&.hpp'\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::camera::Object\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkipr\fP"
.br
.ti -1c
.RI " \fBkipr::camera\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< Object > \fBkipr::camera::ObjectVector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
