.TH "pixel" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <camera\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBg\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int pixel::b"

.SS "int pixel::g"

.SS "int pixel::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
