.TH "point3" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point3 \- A 3D point; has x, y, and z\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometry\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "the x value of the point "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "the y value of the point "
.ti -1c
.RI "int \fBz\fP"
.br
.RI "the z value of the point "
.in -1c
.SH "Detailed Description"
.PP 
A 3D point; has x, y, and z\&. 
.SH "Member Data Documentation"
.PP 
.SS "int point3::x"

.PP
the x value of the point 
.SS "int point3::y"

.PP
the y value of the point 
.SS "int point3::z"

.PP
the z value of the point 

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
