.TH "rectangle" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rectangle \- A rectangle object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometry\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBulx\fP"
.br
.RI "the x value of the rectangle's upper left "
.ti -1c
.RI "int \fBuly\fP"
.br
.RI "the y value of the rectangle's upper left "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "the width of the rectangle "
.ti -1c
.RI "int \fBheight\fP"
.br
.RI "the height of the rectangle "
.in -1c
.SH "Detailed Description"
.PP 
A rectangle object\&. 
.SH "Member Data Documentation"
.PP 
.SS "int rectangle::height"

.PP
the height of the rectangle 
.SS "int rectangle::ulx"

.PP
the x value of the rectangle's upper left 
.SS "int rectangle::uly"

.PP
the y value of the rectangle's upper left 
.SS "int rectangle::width"

.PP
the width of the rectangle 

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
