.TH "Rgb" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rgb
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <color\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBr\fP"
.br
.ti -1c
.RI "unsigned char \fBg\fP"
.br
.ti -1c
.RI "unsigned char \fBb\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char Rgb::b"

.SS "unsigned char Rgb::g"

.SS "unsigned char Rgb::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
