.TH "/home/zachary/libwallaby/module/servo/public/kipr/servo/servo.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/servo/public/kipr/servo/servo.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBenable_servo\fP (int port)"
.br
.RI "Enable a specific servo\&. "
.ti -1c
.RI "void \fBdisable_servo\fP (int port)"
.br
.RI "Disable a specific servo\&. "
.ti -1c
.RI "void \fBenable_servos\fP ()"
.br
.RI "Enable all four servo channels\&. "
.ti -1c
.RI "void \fBdisable_servos\fP ()"
.br
.RI "Disable all four servo channels\&. "
.ti -1c
.RI "void \fBset_servo_enabled\fP (int port, int enabled)"
.br
.RI "Enable or disable a specific servo\&. "
.ti -1c
.RI "int \fBget_servo_enabled\fP (int port)"
.br
.RI "Check if a servo is enabled\&. "
.ti -1c
.RI "int \fBget_servo_position\fP (int port)"
.br
.RI "Get the most recent commanded servo position\&. "
.ti -1c
.RI "void \fBset_servo_position\fP (int port, int position)"
.br
.RI "Set a new servo goal position\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
