.TH "/home/zachary/libwallaby/module/network/public/kipr/network/socket.hpp" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/network/public/kipr/network/socket.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddress\fP"
.br
.ti -1c
.RI "class \fBSocket\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBsocket_fd_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBsocket_fd_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
