.TH "std::hash< kipr::log::Level >" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::hash< kipr::log::Level >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBkipr::log::Level\fP &level) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t std::hash< \fBkipr::log::Level\fP >::operator() (const \fBkipr::log::Level\fP & level) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
