.TH "/home/zachary/libwallaby/module/tello/public/kipr/tello/tello.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/tello/public/kipr/tello/tello.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBtellos_find\fP ()"
.br
.ti -1c
.RI "int \fBtello_connect\fP (char const *tello)"
.br
.ti -1c
.RI "int \fBwpa_cmd\fP (char const *cmd, char *buf)"
.br
.ti -1c
.RI "int \fBtello_send\fP (char const *command)"
.br
.ti -1c
.RI "int \fBwpa_sup_connect\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int tello_connect (char const * tello)"

.SS "int tello_send (char const * command)"

.SS "char* tellos_find ()"

.SS "int wpa_cmd (char const * cmd, char * buf)"

.SS "int wpa_sup_connect ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
