.TH "/home/zachary/libwallaby/module/thread/public/kipr/thread/thread.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/thread/public/kipr/thread/thread.h \- Threading methods\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'kipr/export/export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmutex\fP"
.br
.RI "A mutex, or lock\&. "
.ti -1c
.RI "struct \fBthread\fP"
.br
.RI "A thread, or separate process\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBthread_function\fP) ()"
.br
.RI "thread_function is a wrapper for functions of all return types\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBmutex\fP \fBmutex_create\fP ()"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBmutex_lock\fP (\fBmutex\fP m)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP int \fBmutex_trylock\fP (\fBmutex\fP m)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBmutex_unlock\fP (\fBmutex\fP m)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBmutex_destroy\fP (\fBmutex\fP m)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP \fBthread\fP \fBthread_create\fP (\fBthread_function\fP func)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBthread_start\fP (\fBthread\fP id)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBthread_wait\fP (\fBthread\fP id)"
.br
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBthread_destroy\fP (\fBthread\fP id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Threading methods\&. 


.PP
\fBAuthor\fP
.RS 4
Braden McDorman 
.RE
.PP
\fBCopyright\fP
.RS 4
KISS Insitute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
