.TH "thread" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread \- A thread, or separate process\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "a C++ Thread object cast to a \fCvoid*\fP\&. Not intended to be accessed\&. "
.in -1c
.SH "Detailed Description"
.PP 
A thread, or separate process\&. 

a thread runs a function 'in the background' (while another function is executing)\&. 
.PP
\fBSee also\fP
.RS 4
\fBthread_create\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "void* thread::data"

.PP
a C++ Thread object cast to a \fCvoid*\fP\&. Not intended to be accessed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
