.TH "/home/zachary/libwallaby/module/time/public/kipr/time/time.h" 3 "Mon Sep 12 2022" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/zachary/libwallaby/module/time/public/kipr/time/time.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmsleep\fP (long msecs)"
.br
.ti -1c
.RI "unsigned long \fBsystime\fP ()"
.br
.ti -1c
.RI "double \fBseconds\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void msleep (long msecs)"

.SS "double seconds ()"

.SS "unsigned long systime ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
