libkipr: kipr::log::Log Class Reference
kipr::log::Log Class Reference
#include <log.hpp>
Public Types
typedef std::shared_ptr< Log > Ptr
typedef std::shared_ptr< const Log > ConstPtr
Public Member Functions
Log (const std::string &module)
Log (Log &&rhs)
void log (const Level level, const std::string &message, const Location &location)
void log (const Level level, const std::string &message)
LogStream log (const Level level)
void fatal (const std::string &message, const Location &location)
void fatal (const std::string &message)
LogStream fatal ()
void error (const std::string &message, const Location &location)
void error (const std::string &message)
LogStream error ()
void warning (const std::string &message, const Location &location)
void warning (const std::string &message)
LogStream warning ()
void info (const std::string &message, const Location &location)
void info (const std::string &message)
LogStream info ()
void debug (const std::string &message, const Location &location)
void debug (const std::string &message)
LogStream debug ()
void verbose (const std::string &message, const Location &location)
void verbose (const std::string &message)
LogStream verbose ()
Member Typedef Documentation
ConstPtr
typedef std::shared_ptr<const Log> kipr::log::Log::ConstPtr
Ptr
typedef std::shared_ptr<Log> kipr::log::Log::Ptr
Constructor & Destructor Documentation
Log() [1/2]
kipr::log::Log::Log (const std::string & module)
Log() [2/2]
kipr::log::Log::Log (Log && rhs)
Member Function Documentation
debug() [1/3]
LogStream kipr::log::Log::debug () inline
References kipr::log::Debug, and log().
debug() [2/3]
void kipr::log::Log::debug (const std::string & message) inline
References kipr::log::Debug, and log().
debug() [3/3]
void kipr::log::Log::debug (const std::string & message, const Location & location) inline
References kipr::log::Debug, and log().
error() [1/3]
LogStream kipr::log::Log::error () inline
References kipr::log::Error, and log().
error() [2/3]
void kipr::log::Log::error (const std::string & message) inline
References kipr::log::Error, and log().
error() [3/3]
void kipr::log::Log::error (const std::string & message, const Location & location) inline
References kipr::log::Error, and log().
fatal() [1/3]
LogStream kipr::log::Log::fatal () inline
References kipr::log::Fatal, and log().
fatal() [2/3]
void kipr::log::Log::fatal (const std::string & message) inline
References kipr::log::Fatal, and log().
fatal() [3/3]
void kipr::log::Log::fatal (const std::string & message, const Location & location) inline
References kipr::log::Fatal, and log().
info() [1/3]
LogStream kipr::log::Log::info () inline
References kipr::log::Info, and log().
info() [2/3]
void kipr::log::Log::info (const std::string & message) inline
References kipr::log::Info, and log().
info() [3/3]
void kipr::log::Log::info (const std::string & message, const Location & location) inline
References kipr::log::Info, and log().
log() [1/3]
LogStream kipr::log::Log::log (const Level level)
log() [2/3]
void kipr::log::Log::log (const Level level, const std::string & message)
log() [3/3]
void kipr::log::Log::log (const Level level, const std::string & message, const Location & location)
Referenced by debug(), error(), fatal(), info(), verbose(), and warning().
verbose() [1/3]
LogStream kipr::log::Log::verbose () inline
References log(), and kipr::log::Verbose.
verbose() [2/3]
void kipr::log::Log::verbose (const std::string & message) inline
References log(), and kipr::log::Verbose.
verbose() [3/3]
void kipr::log::Log::verbose (const std::string & message, const Location & location) inline
References log(), and kipr::log::Verbose.
warning() [1/3]
LogStream kipr::log::Log::warning () inline
References log(), and kipr::log::Warning.
warning() [2/3]
void kipr::log::Log::warning (const std::string & message) inline
References log(), and kipr::log::Warning.
warning() [3/3]
void kipr::log::Log::warning (const std::string & message, const Location & location) inline
References log(), and kipr::log::Warning.
The documentation for this class was generated from the following file:
/home/zachary/libwallaby/module/log/public/kipr/log/log.hpp