libkipr: /home/zachary/libwallaby/module/geometry/public/kipr/geometry/geometry.h File Reference
geometry.h File Reference
#include "kipr/export/export.h"
Classes
struct point2
A 2D point; has x and y.
struct point3
A 3D point; has x, y, and z.
struct rectangle
A rectangle object.
Typedefs
typedef struct point2 point2
A 2D point; has x and y.
typedef struct point3 point3
A 3D point; has x, y, and z.
typedef struct rectangle rectangle
A rectangle object.
Functions
EXPORT_SYM point2 create_point2 (int x, int y)
Create a point2 object.
EXPORT_SYM point3 create_point3 (int x, int y, int z)
Create a point3 object.
EXPORT_SYM rectangle create_rectangle (int ulx, int uly, int width, int height)
Create a rectangle object.
Typedef Documentation
point2
typedef struct point2 point2
A 2D point; has x and y.
point3
typedef struct point3 point3
A 3D point; has x, y, and z.
rectangle
typedef struct rectangle rectangle
A rectangle object.
Function Documentation
create_point2()
EXPORT_SYM point2 create_point2 (int x, int y)
Create a point2 object.
Parameters
x - the x value of the point
y - the y value of the point
Returns
point2 object
Referenced by kipr::geometry::Point2< T >::toCPoint2().
create_point3()
EXPORT_SYM point3 create_point3 (int x, int y, int z)
Create a point3 object.
Parameters
x - the x value of the point
y - the y value of the point
z - the z value of the point
Returns
point3 object
Referenced by kipr::geometry::Point3< T >::toCPoint3().
create_rectangle()
EXPORT_SYM rectangle create_rectangle (int ulx, int uly, int width, int height)
Create a rectangle object.
Parameters
ulx - the x value of the rectangle's upper left
uly - the y value of the rectangle's upper left
width - the width of the rectangle
height - the height of the rectangle
Returns
rectangle object
Referenced by kipr::geometry::Rect< T >::toCRectangle().